// SPDX-FileCopyrightText: 2021-2023 deroad <wargio@libero.it>
// SPDX-License-Identifier: LGPL-3.0-only

#include "minunit.h"

mu_demangle_tests(gpl,

	mu_demangle_test("_ZN4llvmL14OperandInfo256E", "llvm::OperandInfo256"),
	mu_demangle_test("_ZN4llvmL14OperandInfo257E", "llvm::OperandInfo257"),
	mu_demangle_test("_ZN4llvmL14OperandInfo258E", "llvm::OperandInfo258"),
	mu_demangle_test("_ZN4llvmL14OperandInfo259E", "llvm::OperandInfo259"),
	mu_demangle_test("_ZN4llvmL14OperandInfo260E", "llvm::OperandInfo260"),
	mu_demangle_test("_ZN4llvmL14OperandInfo261E", "llvm::OperandInfo261"),
	mu_demangle_test("_ZN4llvmL8X86InstsE", "llvm::X86Insts"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L19RegisterDescriptorsE", "llvm::(anonymous namespace)::RegisterDescriptors"),
	mu_demangle_test("_ZL9SubTypeKV", "SubTypeKV"),
	mu_demangle_test("_ZL9FeatureKV", "FeatureKV"),
	mu_demangle_test("_ZL10MatchTable", "MatchTable"),
	mu_demangle_test("_ZL17OperandMatchTable", "OperandMatchTable"),
	mu_demangle_test("_ZN4llvmL9Barriers1E", "llvm::Barriers1"),
	mu_demangle_test("_ZN4llvmL9Barriers2E", "llvm::Barriers2"),
	mu_demangle_test("_ZN4llvmL9Barriers3E", "llvm::Barriers3"),
	mu_demangle_test("_ZN4llvmL9Barriers4E", "llvm::Barriers4"),
	mu_demangle_test("_ZN4llvmL9Barriers5E", "llvm::Barriers5"),
	mu_demangle_test("_ZN4llvmL9Barriers6E", "llvm::Barriers6"),
	mu_demangle_test("_ZN4llvmL9Barriers7E", "llvm::Barriers7"),
	mu_demangle_test("_ZN4llvmL9Barriers8E", "llvm::Barriers8"),
	mu_demangle_test("_ZN4llvmL12OperandInfo2E", "llvm::OperandInfo2"),
	mu_demangle_test("_ZN4llvmL12OperandInfo3E", "llvm::OperandInfo3"),
	mu_demangle_test("_ZN4llvmL12OperandInfo4E", "llvm::OperandInfo4"),
	mu_demangle_test("_ZN4llvmL12OperandInfo5E", "llvm::OperandInfo5"),
	mu_demangle_test("_ZN4llvmL12OperandInfo6E", "llvm::OperandInfo6"),
	mu_demangle_test("_ZN4llvmL12OperandInfo7E", "llvm::OperandInfo7"),
	mu_demangle_test("_ZN4llvmL12OperandInfo8E", "llvm::OperandInfo8"),
	mu_demangle_test("_ZN4llvmL12OperandInfo9E", "llvm::OperandInfo9"),
	mu_demangle_test("_ZN4llvmL13OperandInfo10E", "llvm::OperandInfo10"),
	mu_demangle_test("_ZN4llvmL13OperandInfo11E", "llvm::OperandInfo11"),
	mu_demangle_test("_ZN4llvmL13OperandInfo12E", "llvm::OperandInfo12"),
	mu_demangle_test("_ZN4llvmL13OperandInfo13E", "llvm::OperandInfo13"),
	mu_demangle_test("_ZN4llvmL13OperandInfo14E", "llvm::OperandInfo14"),
	mu_demangle_test("_ZN4llvmL13OperandInfo15E", "llvm::OperandInfo15"),
	mu_demangle_test("_ZN4llvmL13OperandInfo16E", "llvm::OperandInfo16"),
	mu_demangle_test("_ZN4llvmL13OperandInfo17E", "llvm::OperandInfo17"),
	mu_demangle_test("_ZN4llvmL13OperandInfo18E", "llvm::OperandInfo18"),
	mu_demangle_test("_ZN4llvmL13OperandInfo19E", "llvm::OperandInfo19"),
	mu_demangle_test("_ZN4llvmL13OperandInfo20E", "llvm::OperandInfo20"),
	mu_demangle_test("_ZN4llvmL13OperandInfo21E", "llvm::OperandInfo21"),
	mu_demangle_test("_ZN4llvmL13OperandInfo22E", "llvm::OperandInfo22"),
	mu_demangle_test("_ZN4llvmL13OperandInfo23E", "llvm::OperandInfo23"),
	mu_demangle_test("_ZN4llvmL13OperandInfo24E", "llvm::OperandInfo24"),
	mu_demangle_test("_ZN4llvmL13OperandInfo25E", "llvm::OperandInfo25"),
	mu_demangle_test("_ZN4llvmL13OperandInfo26E", "llvm::OperandInfo26"),
	mu_demangle_test("_ZN4llvmL13OperandInfo27E", "llvm::OperandInfo27"),
	mu_demangle_test("_ZN4llvmL13OperandInfo28E", "llvm::OperandInfo28"),
	mu_demangle_test("_ZN4llvmL13OperandInfo29E", "llvm::OperandInfo29"),
	mu_demangle_test("_ZN4llvmL13OperandInfo30E", "llvm::OperandInfo30"),
	mu_demangle_test("_ZN4llvmL13OperandInfo31E", "llvm::OperandInfo31"),
	mu_demangle_test("_ZN4llvmL13OperandInfo32E", "llvm::OperandInfo32"),
	mu_demangle_test("_ZN4llvmL13OperandInfo33E", "llvm::OperandInfo33"),
	mu_demangle_test("_ZN4llvmL13OperandInfo34E", "llvm::OperandInfo34"),
	mu_demangle_test("_ZN4llvmL13OperandInfo35E", "llvm::OperandInfo35"),
	mu_demangle_test("_ZN4llvmL13OperandInfo36E", "llvm::OperandInfo36"),
	mu_demangle_test("_ZN4llvmL13OperandInfo37E", "llvm::OperandInfo37"),
	mu_demangle_test("_ZN4llvmL13OperandInfo38E", "llvm::OperandInfo38"),
	mu_demangle_test("_ZN4llvmL13OperandInfo39E", "llvm::OperandInfo39"),
	mu_demangle_test("_ZN4llvmL13OperandInfo40E", "llvm::OperandInfo40"),
	mu_demangle_test("_ZN4llvmL13OperandInfo41E", "llvm::OperandInfo41"),
	mu_demangle_test("_ZN4llvmL13OperandInfo42E", "llvm::OperandInfo42"),
	mu_demangle_test("_ZN4llvmL13OperandInfo43E", "llvm::OperandInfo43"),
	mu_demangle_test("_ZN4llvmL13OperandInfo44E", "llvm::OperandInfo44"),
	mu_demangle_test("_ZN4llvmL13OperandInfo45E", "llvm::OperandInfo45"),
	mu_demangle_test("_ZN4llvmL13OperandInfo46E", "llvm::OperandInfo46"),
	mu_demangle_test("_ZN4llvmL13OperandInfo47E", "llvm::OperandInfo47"),
	mu_demangle_test("_ZN4llvmL13OperandInfo48E", "llvm::OperandInfo48"),
	mu_demangle_test("_ZN4llvmL13OperandInfo49E", "llvm::OperandInfo49"),
	mu_demangle_test("_ZN4llvmL13OperandInfo50E", "llvm::OperandInfo50"),
	mu_demangle_test("_ZN4llvmL13OperandInfo51E", "llvm::OperandInfo51"),
	mu_demangle_test("_ZN4llvmL13OperandInfo52E", "llvm::OperandInfo52"),
	mu_demangle_test("_ZN4llvmL13OperandInfo53E", "llvm::OperandInfo53"),
	mu_demangle_test("_ZN4llvmL13OperandInfo54E", "llvm::OperandInfo54"),
	mu_demangle_test("_ZN4llvmL13OperandInfo55E", "llvm::OperandInfo55"),
	mu_demangle_test("_ZN4llvmL13OperandInfo56E", "llvm::OperandInfo56"),
	mu_demangle_test("_ZN4llvmL13OperandInfo57E", "llvm::OperandInfo57"),
	mu_demangle_test("_ZN4llvmL13OperandInfo58E", "llvm::OperandInfo58"),
	mu_demangle_test("_ZN4llvmL13OperandInfo59E", "llvm::OperandInfo59"),
	mu_demangle_test("_ZN4llvmL13OperandInfo60E", "llvm::OperandInfo60"),
	mu_demangle_test("_ZN4llvmL13OperandInfo61E", "llvm::OperandInfo61"),
	mu_demangle_test("_ZN4llvmL13OperandInfo62E", "llvm::OperandInfo62"),
	mu_demangle_test("_ZN4llvmL13OperandInfo63E", "llvm::OperandInfo63"),
	mu_demangle_test("_ZN4llvmL13OperandInfo64E", "llvm::OperandInfo64"),
	mu_demangle_test("_ZN4llvmL13OperandInfo65E", "llvm::OperandInfo65"),
	mu_demangle_test("_ZN4llvmL13OperandInfo66E", "llvm::OperandInfo66"),
	mu_demangle_test("_ZN4llvmL13OperandInfo67E", "llvm::OperandInfo67"),
	mu_demangle_test("_ZN4llvmL13OperandInfo68E", "llvm::OperandInfo68"),
	mu_demangle_test("_ZN4llvmL13OperandInfo69E", "llvm::OperandInfo69"),
	mu_demangle_test("_ZN4llvmL13OperandInfo70E", "llvm::OperandInfo70"),
	mu_demangle_test("_ZN4llvmL13OperandInfo71E", "llvm::OperandInfo71"),
	mu_demangle_test("_ZN4llvmL13OperandInfo72E", "llvm::OperandInfo72"),
	mu_demangle_test("_ZN4llvmL13OperandInfo73E", "llvm::OperandInfo73"),
	mu_demangle_test("_ZN4llvmL13OperandInfo74E", "llvm::OperandInfo74"),
	mu_demangle_test("_ZN4llvmL13OperandInfo75E", "llvm::OperandInfo75"),
	mu_demangle_test("_ZN4llvmL13OperandInfo76E", "llvm::OperandInfo76"),
	mu_demangle_test("_ZN4llvmL13OperandInfo77E", "llvm::OperandInfo77"),
	mu_demangle_test("_ZN4llvmL13OperandInfo78E", "llvm::OperandInfo78"),
	mu_demangle_test("_ZN4llvmL13OperandInfo79E", "llvm::OperandInfo79"),
	mu_demangle_test("_ZN4llvmL13OperandInfo80E", "llvm::OperandInfo80"),
	mu_demangle_test("_ZN4llvmL13OperandInfo81E", "llvm::OperandInfo81"),
	mu_demangle_test("_ZN4llvmL13OperandInfo82E", "llvm::OperandInfo82"),
	mu_demangle_test("_ZN4llvmL13OperandInfo83E", "llvm::OperandInfo83"),
	mu_demangle_test("_ZN4llvmL13OperandInfo84E", "llvm::OperandInfo84"),
	mu_demangle_test("_ZN4llvmL13OperandInfo85E", "llvm::OperandInfo85"),
	mu_demangle_test("_ZN4llvmL13OperandInfo86E", "llvm::OperandInfo86"),
	mu_demangle_test("_ZN4llvmL13OperandInfo87E", "llvm::OperandInfo87"),
	mu_demangle_test("_ZN4llvmL13OperandInfo88E", "llvm::OperandInfo88"),
	mu_demangle_test("_ZN4llvmL13OperandInfo89E", "llvm::OperandInfo89"),
	mu_demangle_test("_ZN4llvmL13OperandInfo90E", "llvm::OperandInfo90"),
	mu_demangle_test("_ZN4llvmL13OperandInfo91E", "llvm::OperandInfo91"),
	mu_demangle_test("_ZN4llvmL13OperandInfo92E", "llvm::OperandInfo92"),
	mu_demangle_test("_ZN4llvmL13OperandInfo93E", "llvm::OperandInfo93"),
	mu_demangle_test("_ZN4llvmL13OperandInfo94E", "llvm::OperandInfo94"),
	mu_demangle_test("_ZN4llvmL13OperandInfo95E", "llvm::OperandInfo95"),
	mu_demangle_test("_ZN4llvmL13OperandInfo96E", "llvm::OperandInfo96"),
	mu_demangle_test("_ZN4llvmL13OperandInfo97E", "llvm::OperandInfo97"),
	mu_demangle_test("_ZN4llvmL13OperandInfo98E", "llvm::OperandInfo98"),
	mu_demangle_test("_ZN4llvmL13OperandInfo99E", "llvm::OperandInfo99"),
	mu_demangle_test("_ZN4llvmL14OperandInfo100E", "llvm::OperandInfo100"),
	mu_demangle_test("_ZN4llvmL14OperandInfo101E", "llvm::OperandInfo101"),
	mu_demangle_test("_ZN4llvmL14OperandInfo102E", "llvm::OperandInfo102"),
	mu_demangle_test("_ZN4llvmL14OperandInfo103E", "llvm::OperandInfo103"),
	mu_demangle_test("_ZN4llvmL14OperandInfo104E", "llvm::OperandInfo104"),
	mu_demangle_test("_ZN4llvmL14OperandInfo105E", "llvm::OperandInfo105"),
	mu_demangle_test("_ZN4llvmL14OperandInfo106E", "llvm::OperandInfo106"),
	mu_demangle_test("_ZN4llvmL14OperandInfo107E", "llvm::OperandInfo107"),
	mu_demangle_test("_ZN4llvmL14OperandInfo108E", "llvm::OperandInfo108"),
	mu_demangle_test("_ZN4llvmL14OperandInfo109E", "llvm::OperandInfo109"),
	mu_demangle_test("_ZN4llvmL14OperandInfo110E", "llvm::OperandInfo110"),
	mu_demangle_test("_ZN4llvmL14OperandInfo111E", "llvm::OperandInfo111"),
	mu_demangle_test("_ZN4llvmL14OperandInfo112E", "llvm::OperandInfo112"),
	mu_demangle_test("_ZN4llvmL14OperandInfo113E", "llvm::OperandInfo113"),
	mu_demangle_test("_ZN4llvmL14OperandInfo114E", "llvm::OperandInfo114"),
	mu_demangle_test("_ZN4llvmL14OperandInfo115E", "llvm::OperandInfo115"),
	mu_demangle_test("_ZN4llvmL14OperandInfo116E", "llvm::OperandInfo116"),
	mu_demangle_test("_ZN4llvmL14OperandInfo117E", "llvm::OperandInfo117"),
	mu_demangle_test("_ZN4llvmL14OperandInfo118E", "llvm::OperandInfo118"),
	mu_demangle_test("_ZN4llvmL14OperandInfo119E", "llvm::OperandInfo119"),
	mu_demangle_test("_ZN4llvmL14OperandInfo120E", "llvm::OperandInfo120"),
	mu_demangle_test("_ZN4llvmL14OperandInfo121E", "llvm::OperandInfo121"),
	mu_demangle_test("_ZN4llvmL14OperandInfo122E", "llvm::OperandInfo122"),
	mu_demangle_test("_ZN4llvmL14OperandInfo123E", "llvm::OperandInfo123"),
	mu_demangle_test("_ZN4llvmL14OperandInfo124E", "llvm::OperandInfo124"),
	mu_demangle_test("_ZN4llvmL14OperandInfo125E", "llvm::OperandInfo125"),
	mu_demangle_test("_ZN4llvmL14OperandInfo126E", "llvm::OperandInfo126"),
	mu_demangle_test("_ZN4llvmL14OperandInfo127E", "llvm::OperandInfo127"),
	mu_demangle_test("_ZN4llvmL14OperandInfo128E", "llvm::OperandInfo128"),
	mu_demangle_test("_ZN4llvmL14OperandInfo129E", "llvm::OperandInfo129"),
	mu_demangle_test("_ZN4llvmL14OperandInfo130E", "llvm::OperandInfo130"),
	mu_demangle_test("_ZN4llvmL14OperandInfo131E", "llvm::OperandInfo131"),
	mu_demangle_test("_ZN4llvmL14OperandInfo132E", "llvm::OperandInfo132"),
	mu_demangle_test("_ZN4llvmL14OperandInfo133E", "llvm::OperandInfo133"),
	mu_demangle_test("_ZN4llvmL14OperandInfo134E", "llvm::OperandInfo134"),
	mu_demangle_test("_ZN4llvmL14OperandInfo135E", "llvm::OperandInfo135"),
	mu_demangle_test("_ZN4llvmL14OperandInfo136E", "llvm::OperandInfo136"),
	mu_demangle_test("_ZN4llvmL14OperandInfo137E", "llvm::OperandInfo137"),
	mu_demangle_test("_ZN4llvmL14OperandInfo138E", "llvm::OperandInfo138"),
	mu_demangle_test("_ZN4llvmL14OperandInfo139E", "llvm::OperandInfo139"),
	mu_demangle_test("_ZN4llvmL14OperandInfo140E", "llvm::OperandInfo140"),
	mu_demangle_test("_ZN4llvmL14OperandInfo141E", "llvm::OperandInfo141"),
	mu_demangle_test("_ZN4llvmL14OperandInfo142E", "llvm::OperandInfo142"),
	mu_demangle_test("_ZN4llvmL14OperandInfo143E", "llvm::OperandInfo143"),
	mu_demangle_test("_ZN4llvmL14OperandInfo144E", "llvm::OperandInfo144"),
	mu_demangle_test("_ZN4llvmL14OperandInfo145E", "llvm::OperandInfo145"),
	mu_demangle_test("_ZN4llvmL14OperandInfo146E", "llvm::OperandInfo146"),
	mu_demangle_test("_ZN4llvmL14OperandInfo147E", "llvm::OperandInfo147"),
	mu_demangle_test("_ZN4llvmL14OperandInfo148E", "llvm::OperandInfo148"),
	mu_demangle_test("_ZN4llvmL14OperandInfo149E", "llvm::OperandInfo149"),
	mu_demangle_test("_ZN4llvmL14OperandInfo150E", "llvm::OperandInfo150"),
	mu_demangle_test("_ZN4llvmL14OperandInfo151E", "llvm::OperandInfo151"),
	mu_demangle_test("_ZN4llvmL14OperandInfo152E", "llvm::OperandInfo152"),
	mu_demangle_test("_ZN4llvmL14OperandInfo153E", "llvm::OperandInfo153"),
	mu_demangle_test("_ZN4llvmL14OperandInfo154E", "llvm::OperandInfo154"),
	mu_demangle_test("_ZN4llvmL14OperandInfo155E", "llvm::OperandInfo155"),
	mu_demangle_test("_ZN4llvmL14OperandInfo156E", "llvm::OperandInfo156"),
	mu_demangle_test("_ZN4llvmL14OperandInfo157E", "llvm::OperandInfo157"),
	mu_demangle_test("_ZN4llvmL14OperandInfo158E", "llvm::OperandInfo158"),
	mu_demangle_test("_ZN4llvmL14OperandInfo159E", "llvm::OperandInfo159"),
	mu_demangle_test("_ZN4llvmL14OperandInfo160E", "llvm::OperandInfo160"),
	mu_demangle_test("_ZN4llvmL14OperandInfo161E", "llvm::OperandInfo161"),
	mu_demangle_test("_ZN4llvmL14OperandInfo162E", "llvm::OperandInfo162"),
	mu_demangle_test("_ZN4llvmL14OperandInfo163E", "llvm::OperandInfo163"),
	mu_demangle_test("_ZN4llvmL14OperandInfo164E", "llvm::OperandInfo164"),
	mu_demangle_test("_ZN4llvmL14OperandInfo165E", "llvm::OperandInfo165"),
	mu_demangle_test("_ZN4llvmL14OperandInfo166E", "llvm::OperandInfo166"),
	mu_demangle_test("_ZN4llvmL14OperandInfo167E", "llvm::OperandInfo167"),
	mu_demangle_test("_ZN4llvmL14OperandInfo168E", "llvm::OperandInfo168"),
	mu_demangle_test("_ZN4llvmL14OperandInfo169E", "llvm::OperandInfo169"),
	mu_demangle_test("_ZN4llvmL14OperandInfo170E", "llvm::OperandInfo170"),
	mu_demangle_test("_ZN4llvmL14OperandInfo171E", "llvm::OperandInfo171"),
	mu_demangle_test("_ZN4llvmL14OperandInfo172E", "llvm::OperandInfo172"),
	mu_demangle_test("_ZN4llvmL14OperandInfo173E", "llvm::OperandInfo173"),
	mu_demangle_test("_ZN4llvmL14OperandInfo174E", "llvm::OperandInfo174"),
	mu_demangle_test("_ZN4llvmL14OperandInfo175E", "llvm::OperandInfo175"),
	mu_demangle_test("_ZN4llvmL14OperandInfo176E", "llvm::OperandInfo176"),
	mu_demangle_test("_ZN4llvmL14OperandInfo177E", "llvm::OperandInfo177"),
	mu_demangle_test("_ZN4llvmL14OperandInfo178E", "llvm::OperandInfo178"),
	mu_demangle_test("_ZN4llvmL14OperandInfo179E", "llvm::OperandInfo179"),
	mu_demangle_test("_ZN4llvmL14OperandInfo180E", "llvm::OperandInfo180"),
	mu_demangle_test("_ZN4llvmL14OperandInfo181E", "llvm::OperandInfo181"),
	mu_demangle_test("_ZN4llvmL14OperandInfo182E", "llvm::OperandInfo182"),
	mu_demangle_test("_ZN4llvmL14OperandInfo183E", "llvm::OperandInfo183"),
	mu_demangle_test("_ZN4llvmL14OperandInfo184E", "llvm::OperandInfo184"),
	mu_demangle_test("_ZN4llvmL14OperandInfo185E", "llvm::OperandInfo185"),
	mu_demangle_test("_ZN4llvmL14OperandInfo186E", "llvm::OperandInfo186"),
	mu_demangle_test("_ZN4llvmL14OperandInfo187E", "llvm::OperandInfo187"),
	mu_demangle_test("_ZN4llvmL14OperandInfo188E", "llvm::OperandInfo188"),
	mu_demangle_test("_ZN4llvmL14OperandInfo189E", "llvm::OperandInfo189"),
	mu_demangle_test("_ZN4llvmL14OperandInfo190E", "llvm::OperandInfo190"),
	mu_demangle_test("_ZN4llvmL14OperandInfo191E", "llvm::OperandInfo191"),
	mu_demangle_test("_ZN4llvmL14OperandInfo192E", "llvm::OperandInfo192"),
	mu_demangle_test("_ZN4llvmL14OperandInfo193E", "llvm::OperandInfo193"),
	mu_demangle_test("_ZN4llvmL14OperandInfo194E", "llvm::OperandInfo194"),
	mu_demangle_test("_ZN4llvmL14OperandInfo195E", "llvm::OperandInfo195"),
	mu_demangle_test("_ZN4llvmL14OperandInfo196E", "llvm::OperandInfo196"),
	mu_demangle_test("_ZN4llvmL14OperandInfo197E", "llvm::OperandInfo197"),
	mu_demangle_test("_ZN4llvmL14OperandInfo198E", "llvm::OperandInfo198"),
	mu_demangle_test("_ZN4llvmL14OperandInfo199E", "llvm::OperandInfo199"),
	mu_demangle_test("_ZN4llvmL14OperandInfo200E", "llvm::OperandInfo200"),
	mu_demangle_test("_ZN4llvmL14OperandInfo201E", "llvm::OperandInfo201"),
	mu_demangle_test("_ZN4llvmL14OperandInfo202E", "llvm::OperandInfo202"),
	mu_demangle_test("_ZN4llvmL14OperandInfo203E", "llvm::OperandInfo203"),
	mu_demangle_test("_ZN4llvmL14OperandInfo204E", "llvm::OperandInfo204"),
	mu_demangle_test("_ZN4llvmL14OperandInfo205E", "llvm::OperandInfo205"),
	mu_demangle_test("_ZN4llvmL14OperandInfo206E", "llvm::OperandInfo206"),
	mu_demangle_test("_ZN4llvmL14OperandInfo207E", "llvm::OperandInfo207"),
	mu_demangle_test("_ZN4llvmL14OperandInfo208E", "llvm::OperandInfo208"),
	mu_demangle_test("_ZN4llvmL14OperandInfo209E", "llvm::OperandInfo209"),
	mu_demangle_test("_ZN4llvmL14OperandInfo210E", "llvm::OperandInfo210"),
	mu_demangle_test("_ZN4llvmL14OperandInfo211E", "llvm::OperandInfo211"),
	mu_demangle_test("_ZN4llvmL14OperandInfo212E", "llvm::OperandInfo212"),
	mu_demangle_test("_ZN4llvmL14OperandInfo213E", "llvm::OperandInfo213"),
	mu_demangle_test("_ZN4llvmL14OperandInfo214E", "llvm::OperandInfo214"),
	mu_demangle_test("_ZN4llvmL14OperandInfo215E", "llvm::OperandInfo215"),
	mu_demangle_test("_ZN4llvmL14OperandInfo216E", "llvm::OperandInfo216"),
	mu_demangle_test("_ZN4llvmL14OperandInfo217E", "llvm::OperandInfo217"),
	mu_demangle_test("_ZN4llvmL14OperandInfo218E", "llvm::OperandInfo218"),
	mu_demangle_test("_ZN4llvmL14OperandInfo219E", "llvm::OperandInfo219"),
	mu_demangle_test("_ZN4llvmL14OperandInfo220E", "llvm::OperandInfo220"),
	mu_demangle_test("_ZN4llvmL14OperandInfo221E", "llvm::OperandInfo221"),
	mu_demangle_test("_ZN4llvmL14OperandInfo222E", "llvm::OperandInfo222"),
	mu_demangle_test("_ZN4llvmL14OperandInfo223E", "llvm::OperandInfo223"),
	mu_demangle_test("_ZN4llvmL14OperandInfo224E", "llvm::OperandInfo224"),
	mu_demangle_test("_ZN4llvmL14OperandInfo225E", "llvm::OperandInfo225"),
	mu_demangle_test("_ZN4llvmL14OperandInfo226E", "llvm::OperandInfo226"),
	mu_demangle_test("_ZN4llvmL14OperandInfo227E", "llvm::OperandInfo227"),
	mu_demangle_test("_ZN4llvmL14OperandInfo228E", "llvm::OperandInfo228"),
	mu_demangle_test("_ZN4llvmL14OperandInfo229E", "llvm::OperandInfo229"),
	mu_demangle_test("_ZN4llvmL14OperandInfo230E", "llvm::OperandInfo230"),
	mu_demangle_test("_ZN4llvmL14OperandInfo231E", "llvm::OperandInfo231"),
	mu_demangle_test("_ZN4llvmL14OperandInfo232E", "llvm::OperandInfo232"),
	mu_demangle_test("_ZN4llvmL14OperandInfo233E", "llvm::OperandInfo233"),
	mu_demangle_test("_ZN4llvmL14OperandInfo234E", "llvm::OperandInfo234"),
	mu_demangle_test("_ZN4llvmL14OperandInfo235E", "llvm::OperandInfo235"),
	mu_demangle_test("_ZN4llvmL14OperandInfo236E", "llvm::OperandInfo236"),
	mu_demangle_test("_ZN4llvmL14OperandInfo237E", "llvm::OperandInfo237"),
	mu_demangle_test("_ZN4llvmL14OperandInfo238E", "llvm::OperandInfo238"),
	mu_demangle_test("_ZN4llvmL14OperandInfo239E", "llvm::OperandInfo239"),
	mu_demangle_test("_ZN4llvmL14OperandInfo240E", "llvm::OperandInfo240"),
	mu_demangle_test("_ZN4llvmL14OperandInfo241E", "llvm::OperandInfo241"),
	mu_demangle_test("_ZN4llvmL14OperandInfo242E", "llvm::OperandInfo242"),
	mu_demangle_test("_ZN4llvmL14OperandInfo243E", "llvm::OperandInfo243"),
	mu_demangle_test("_ZN4llvmL14OperandInfo244E", "llvm::OperandInfo244"),
	mu_demangle_test("_ZN4llvmL14OperandInfo245E", "llvm::OperandInfo245"),
	mu_demangle_test("_ZN4llvmL14OperandInfo246E", "llvm::OperandInfo246"),
	mu_demangle_test("_ZN4llvmL14OperandInfo247E", "llvm::OperandInfo247"),
	mu_demangle_test("_ZN4llvmL14OperandInfo248E", "llvm::OperandInfo248"),
	mu_demangle_test("_ZN4llvmL14OperandInfo249E", "llvm::OperandInfo249"),
	mu_demangle_test("_ZN4llvmL14OperandInfo250E", "llvm::OperandInfo250"),
	mu_demangle_test("_ZN4llvmL14OperandInfo251E", "llvm::OperandInfo251"),
	mu_demangle_test("_ZN4llvmL14OperandInfo252E", "llvm::OperandInfo252"),
	mu_demangle_test("_ZN4llvmL14OperandInfo253E", "llvm::OperandInfo253"),
	mu_demangle_test("_ZN4llvmL14OperandInfo254E", "llvm::OperandInfo254"),
	mu_demangle_test("_ZN4llvmL14OperandInfo255E", "llvm::OperandInfo255"),
	mu_demangle_test("_ZN4llvmL14OperandInfo256E", "llvm::OperandInfo256"),
	mu_demangle_test("_ZN4llvmL14OperandInfo257E", "llvm::OperandInfo257"),
	mu_demangle_test("_ZN4llvmL14OperandInfo258E", "llvm::OperandInfo258"),
	mu_demangle_test("_ZN4llvmL14OperandInfo259E", "llvm::OperandInfo259"),
	mu_demangle_test("_ZN4llvmL14OperandInfo260E", "llvm::OperandInfo260"),
	mu_demangle_test("_ZN4llvmL8ARMInstsE", "llvm::ARMInsts"),
	mu_demangle_test("_ZL12ARM_MLxTable", "ARM_MLxTable"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L19RegisterDescriptorsE", "llvm::(anonymous namespace)::RegisterDescriptors"),
	mu_demangle_test("_ZL10NumEmitted", "NumEmitted"),
	mu_demangle_test("_ZL6NumTBs", "NumTBs"),
	mu_demangle_test("_ZL6NumCBZ", "NumCBZ"),
	mu_demangle_test("_ZL13NumT2BrShrunk", "NumT2BrShrunk"),
	mu_demangle_test("_ZL13NumT2CPShrunk", "NumT2CPShrunk"),
	mu_demangle_test("_ZL8NumSplit", "NumSplit"),
	mu_demangle_test("_ZL11NumCBrFixed", "NumCBrFixed"),
	mu_demangle_test("_ZL11NumUBrFixed", "NumUBrFixed"),
	mu_demangle_test("_ZL7NumCPEs", "NumCPEs"),
	mu_demangle_test("_ZL13NumJTInserted", "NumJTInserted"),
	mu_demangle_test("_ZL10NumJTMoved", "NumJTMoved"),
	mu_demangle_test("_ZL13NEONLdStTable", "NEONLdStTable"),
	mu_demangle_test("_ZL11NumMovwMovt", "NumMovwMovt"),
	mu_demangle_test("_ZL12NumTailCalls", "NumTailCalls"),
	mu_demangle_test("_ZL12NumVSTMGened", "NumVSTMGened"),
	mu_demangle_test("_ZL12NumVLDMGened", "NumVLDMGened"),
	mu_demangle_test("_ZL11NumSTMGened", "NumSTMGened"),
	mu_demangle_test("_ZL11NumLDMGened", "NumLDMGened"),
	mu_demangle_test("_ZL11NumSTRD2STR", "NumSTRD2STR"),
	mu_demangle_test("_ZL11NumLDRD2LDR", "NumLDRD2LDR"),
	mu_demangle_test("_ZL11NumSTRD2STM", "NumSTRD2STM"),
	mu_demangle_test("_ZL11NumLDRD2LDM", "NumLDRD2LDM"),
	mu_demangle_test("_ZL12NumLdStMoved", "NumLdStMoved"),
	mu_demangle_test("_ZL13NumSTRDFormed", "NumSTRDFormed"),
	mu_demangle_test("_ZL13NumLDRDFormed", "NumLDRDFormed"),
	mu_demangle_test("_ZL12MCNumEmitted", "MCNumEmitted"),
	mu_demangle_test("_ZL18MCNumCPRelocations", "MCNumCPRelocations"),
	mu_demangle_test("_ZL9SubTypeKV", "SubTypeKV"),
	mu_demangle_test("_ZL9FeatureKV", "FeatureKV"),
	mu_demangle_test("_ZL10ProcItinKV", "ProcItinKV"),
	mu_demangle_test("_ZL6Stages", "Stages"),
	mu_demangle_test("_ZL18GenericItineraries", "GenericItineraries"),
	mu_demangle_test("_ZL16ARMV6Itineraries", "ARMV6Itineraries"),
	mu_demangle_test("_ZL19CortexA8Itineraries", "CortexA8Itineraries"),
	mu_demangle_test("_ZL19CortexA9Itineraries", "CortexA9Itineraries"),
	mu_demangle_test("_ZL9NumExpand", "NumExpand"),
	mu_demangle_test("_ZL8NumVMovs", "NumVMovs"),
	mu_demangle_test("_ZL6NumITs", "NumITs"),
	mu_demangle_test("_ZL13NumMovedInsts", "NumMovedInsts"),
	mu_demangle_test("_ZL10NumNarrows", "NumNarrows"),
	mu_demangle_test("_ZL9Num2Addrs", "Num2Addrs"),
	mu_demangle_test("_ZL8NumLdSts", "NumLdSts"),
	mu_demangle_test("_ZN12_GLOBAL__N_1L11ReduceTableE", "(anonymous namespace)::ReduceTable"),
	mu_demangle_test("_ZL13NodesCombined", "NodesCombined"),
	mu_demangle_test("_ZL11OpsNarrowed", "OpsNarrowed"),
	mu_demangle_test("_ZL16PostIndexedNodes", "PostIndexedNodes"),
	mu_demangle_test("_ZL15PreIndexedNodes", "PreIndexedNodes"),
	mu_demangle_test("_ZL10LdStFP2Int", "LdStFP2Int"),
	mu_demangle_test("_ZL8NumNoops", "NumNoops"),
	mu_demangle_test("_ZL9NumStalls", "NumStalls"),
	mu_demangle_test("_ZL11NumPRCopies", "NumPRCopies"),
	mu_demangle_test("_ZL7NumDups", "NumDups"),
	mu_demangle_test("_ZL10NumUnfolds", "NumUnfolds"),
	mu_demangle_test("_ZL13NumBacktracks", "NumBacktracks"),
	mu_demangle_test("_ZL14LoadsClustered", "LoadsClustered"),
	mu_demangle_test("_ZL17NumDAGIselRetries", "NumDAGIselRetries"),
	mu_demangle_test("_ZL17NumFastIselBlocks", "NumFastIselBlocks"),
	mu_demangle_test("_ZL12NumDAGBlocks", "NumDAGBlocks"),
	mu_demangle_test("_ZL19NumFastIselFailures", "NumFastIselFailures"),
	mu_demangle_test("_ZL12EmittedInsts", "EmittedInsts"),
	mu_demangle_test("_ZL13NumBranchOpts", "NumBranchOpts"),
	mu_demangle_test("_ZL13NumDeadBlocks", "NumDeadBlocks"),
	mu_demangle_test("_ZL12NumTailMerge", "NumTailMerge"),
	mu_demangle_test("_ZL15NumLoopsAligned", "NumLoopsAligned"),
	mu_demangle_test("_ZL13NumIntraMoved", "NumIntraMoved"),
	mu_demangle_test("_ZL12NumIntraElim", "NumIntraElim"),
	mu_demangle_test("_ZL10NumDeletes", "NumDeletes"),
	mu_demangle_test("_ZL23NumExceptionValuesMoved", "NumExceptionValuesMoved"),
	mu_demangle_test("_ZL17NumUnwindsLowered", "NumUnwindsLowered"),
	mu_demangle_test("_ZL19NumLandingPadsSplit", "NumLandingPadsSplit"),
	mu_demangle_test("_ZL12NumIfConvBBs", "NumIfConvBBs"),
	mu_demangle_test("_ZL9NumDupBBs", "NumDupBBs"),
	mu_demangle_test("_ZL11NumDiamonds", "NumDiamonds"),
	mu_demangle_test("_ZL15NumTriangleFRev", "NumTriangleFRev"),
	mu_demangle_test("_ZL16NumTriangleFalse", "NumTriangleFalse"),
	mu_demangle_test("_ZL14NumTriangleRev", "NumTriangleRev"),
	mu_demangle_test("_ZL11NumTriangle", "NumTriangle"),
	mu_demangle_test("_ZL14NumSimpleFalse", "NumSimpleFalse"),
	mu_demangle_test("_ZL9NumSimple", "NumSimple"),
	mu_demangle_test("_ZL9numSplits", "numSplits"),
	mu_demangle_test("_ZL8numFolds", "numFolds"),
	mu_demangle_test("_ZL12numIntervals", "numIntervals"),
	mu_demangle_test("_ZL15NumReplacements", "NumReplacements"),
	mu_demangle_test("_ZL16NumBaseRegisters", "NumBaseRegisters"),
	mu_demangle_test("_ZL14NumAllocations", "NumAllocations"),
	mu_demangle_test("_ZL11NumCommutes", "NumCommutes"),
	mu_demangle_test("_ZL11NumPhysCSEs", "NumPhysCSEs"),
	mu_demangle_test("_ZL7NumCSEs", "NumCSEs"),
	mu_demangle_test("_ZL12NumCoalesces", "NumCoalesces"),
	mu_demangle_test("_ZL10NumHoisted", "NumHoisted"),
	mu_demangle_test("_ZL8NumCSEed", "NumCSEed"),
	mu_demangle_test("_ZL8NumLowRP", "NumLowRP"),
	mu_demangle_test("_ZL14NumHighLatency", "NumHighLatency"),
	mu_demangle_test("_ZL16NumPostRAHoisted", "NumPostRAHoisted"),
	mu_demangle_test("_ZL7NumSunk", "NumSunk"),
	mu_demangle_test("_ZL8NumSplit", "NumSplit"),
	mu_demangle_test("_ZL12NumCoalesces", "NumCoalesces"),
	mu_demangle_test("_ZL16NumDeadPHICycles", "NumDeadPHICycles"),
	mu_demangle_test("_ZL12NumPHICycles", "NumPHICycles"),
	mu_demangle_test("_ZL9NumReused", "NumReused"),
	mu_demangle_test("_ZL9NumAtomic", "NumAtomic"),
	mu_demangle_test("_ZL10NumImmFold", "NumImmFold"),
	mu_demangle_test("_ZL8NumReuse", "NumReuse"),
	mu_demangle_test("_ZL13NumEliminated", "NumEliminated"),
	mu_demangle_test("_ZL8NumNoops", "NumNoops"),
	mu_demangle_test("_ZL9NumStalls", "NumStalls"),
	mu_demangle_test("_ZL12NumFixedAnti", "NumFixedAnti"),
	mu_demangle_test("_ZL13NumDeadSpills", "NumDeadSpills"),
	mu_demangle_test("_ZL12NumRenumbers", "NumRenumbers"),
	mu_demangle_test("_ZL15NumRestoreFolds", "NumRestoreFolds"),
	mu_demangle_test("_ZL8NumFolds", "NumFolds"),
	mu_demangle_test("_ZL9NumRemats", "NumRemats"),
	mu_demangle_test("_ZL9NumSplits", "NumSplits"),
	mu_demangle_test("_ZL16NumScavengedRegs", "NumScavengedRegs"),
	mu_demangle_test("_ZL19NumVirtualFrameRegs", "NumVirtualFrameRegs"),
	mu_demangle_test("_ZL9NumCopies", "NumCopies"),
	mu_demangle_test("_ZL9NumStores", "NumStores"),
	mu_demangle_test("_ZL8NumLoads", "NumLoads"),
	mu_demangle_test("_ZL11NumCoalesce", "NumCoalesce"),
	mu_demangle_test("_ZL13NumBacktracks", "NumBacktracks"),
	mu_demangle_test("_ZL12NumDowngrade", "NumDowngrade"),
	mu_demangle_test("_ZL8NumIters", "NumIters"),
	mu_demangle_test("_ZL12numSRReduced", "numSRReduced"),
	mu_demangle_test("_ZL7numPeep", "numPeep"),
	mu_demangle_test("_ZL8numJoins", "numJoins"),
	mu_demangle_test("_ZL11numCrossRCs", "numCrossRCs"),
	mu_demangle_test("_ZL9numAborts", "numAborts"),
	mu_demangle_test("_ZL12numDeadValNo", "numDeadValNo"),
	mu_demangle_test("_ZL9NumReMats", "NumReMats"),
	mu_demangle_test("_ZL11numCommutes", "numCommutes"),
	mu_demangle_test("_ZL10numExtends", "numExtends"),
	mu_demangle_test("_ZL10NumSpilled", "NumSpilled"),
	mu_demangle_test("_ZL10NumUnwinds", "NumUnwinds"),
	mu_demangle_test("_ZL10NumInvokes", "NumInvokes"),
	mu_demangle_test("_ZL7NumDead", "NumDead"),
	mu_demangle_test("_ZL12NumStoreElim", "NumStoreElim"),
	mu_demangle_test("_ZL10NumRegRepl", "NumRegRepl"),
	mu_demangle_test("_ZL11NumLoadElim", "NumLoadElim"),
	mu_demangle_test("_ZL13NumEliminated", "NumEliminated"),
	mu_demangle_test("_ZL13NumDeadBlocks", "NumDeadBlocks"),
	mu_demangle_test("_ZL12NumInstrDups", "NumInstrDups"),
	mu_demangle_test("_ZL11NumTailDups", "NumTailDups"),
	mu_demangle_test("_ZL8NumTails", "NumTails"),
	mu_demangle_test("_ZL9NumReMats", "NumReMats"),
	mu_demangle_test("_ZL19NumConvertedTo3Addr", "NumConvertedTo3Addr"),
	mu_demangle_test("_ZL12Num3AddrSunk", "Num3AddrSunk"),
	mu_demangle_test("_ZL15NumAggrCommuted", "NumAggrCommuted"),
	mu_demangle_test("_ZL11NumCommuted", "NumCommuted"),
	mu_demangle_test("_ZL10NumDeletes", "NumDeletes"),
	mu_demangle_test("_ZL19NumTwoAddressInstrs", "NumTwoAddressInstrs"),
	mu_demangle_test("_ZL9NumSpills", "NumSpills"),
	mu_demangle_test("_ZL6NumDSS", "NumDSS"),
	mu_demangle_test("_ZL9NumStores", "NumStores"),
	mu_demangle_test("_ZL6NumDRM", "NumDRM"),
	mu_demangle_test("_ZL9NumReused", "NumReused"),
	mu_demangle_test("_ZL8NumLoads", "NumLoads"),
	mu_demangle_test("_ZL9NumReMats", "NumReMats"),
	mu_demangle_test("_ZL6NumDCE", "NumDCE"),
	mu_demangle_test("_ZL11NumCommutes", "NumCommutes"),
	mu_demangle_test("_ZL6NumDSE", "NumDSE"),
	mu_demangle_test("_ZL10NumSUnfold", "NumSUnfold"),
	mu_demangle_test("_ZL10NumAvoided", "NumAvoided"),
	mu_demangle_test("_ZL11NumCopified", "NumCopified"),
	mu_demangle_test("_ZL10NumOmitted", "NumOmitted"),
	mu_demangle_test("_ZL10NumPSpills", "NumPSpills"),
	mu_demangle_test("_ZL15NumModRefUnfold", "NumModRefUnfold"),
	mu_demangle_test("_ZL10NumRemoved", "NumRemoved"),
	mu_demangle_test("_ZL11NumGEPsElim", "NumGEPsElim"),
	mu_demangle_test("_ZL14NumMemoryInsts", "NumMemoryInsts"),
	mu_demangle_test("_ZL10NumCmpUses", "NumCmpUses"),
	mu_demangle_test("_ZL10NumExtUses", "NumExtUses"),
	mu_demangle_test("_ZL12NumExtsMoved", "NumExtsMoved"),
	mu_demangle_test("_ZL11NumCastUses", "NumCastUses"),
	mu_demangle_test("_ZL11NumPHIsElim", "NumPHIsElim"),
	mu_demangle_test("_ZL13NumBlocksElim", "NumBlocksElim"),
	mu_demangle_test("_ZL12NumMemAccess", "NumMemAccess"),
	mu_demangle_test("_ZL7NumCmps", "NumCmps"),
	mu_demangle_test("_ZL7NumPhis", "NumPhis"),
	mu_demangle_test("_ZL10NumSelects", "NumSelects"),
	mu_demangle_test("_ZL12NumFastOther", "NumFastOther"),
	mu_demangle_test("_ZL13NumFastStores", "NumFastStores"),
	mu_demangle_test("_ZL6NumDSE", "NumDSE"),
	mu_demangle_test("_ZL10NumCSECall", "NumCSECall"),
	mu_demangle_test("_ZL10NumCSELoad", "NumCSELoad"),
	mu_demangle_test("_ZL6NumCSE", "NumCSE"),
	mu_demangle_test("_ZL11NumSimplify", "NumSimplify"),
	mu_demangle_test("_ZL9NumGVNPRE", "NumGVNPRE"),
	mu_demangle_test("_ZL11NumGVNInstr", "NumGVNInstr"),
	mu_demangle_test("_ZL10NumPRELoad", "NumPRELoad"),
	mu_demangle_test("_ZL10NumGVNLoad", "NumGVNLoad"),
	mu_demangle_test("_ZL12NumGVNBlocks", "NumGVNBlocks"),
	mu_demangle_test("_ZL10NumRemoved", "NumRemoved"),
	mu_demangle_test("_ZL7NumLFTR", "NumLFTR"),
	mu_demangle_test("_ZL11NumInserted", "NumInserted"),
	mu_demangle_test("_ZL11NumReplaced", "NumReplaced"),
	mu_demangle_test("_ZL8NumDupes", "NumDupes"),
	mu_demangle_test("_ZL10NumThreads", "NumThreads"),
	mu_demangle_test("_ZL8NumFolds", "NumFolds"),
	mu_demangle_test("_ZL11NumPromoted", "NumPromoted"),
	mu_demangle_test("_ZL10NumHoisted", "NumHoisted"),
	mu_demangle_test("_ZL13NumMovedCalls", "NumMovedCalls"),
	mu_demangle_test("_ZL13NumMovedLoads", "NumMovedLoads"),
	mu_demangle_test("_ZL7NumSunk", "NumSunk"),
	mu_demangle_test("_ZL10NumDeleted", "NumDeleted"),
	mu_demangle_test("_ZL9NumMemSet", "NumMemSet"),
	mu_demangle_test("_ZL9NumMemCpy", "NumMemCpy"),
	mu_demangle_test("_ZL10NumRotated", "NumRotated"),
	mu_demangle_test("_ZL10NumSelects", "NumSelects"),
	mu_demangle_test("_ZL11NumSwitches", "NumSwitches"),
	mu_demangle_test("_ZL11NumBranches", "NumBranches"),
	mu_demangle_test("_ZL11NumSimplify", "NumSimplify"),
	mu_demangle_test("_ZL10NumTrivial", "NumTrivial"),
	mu_demangle_test("_ZL14NumMemCpyInstr", "NumMemCpyInstr"),
	mu_demangle_test("_ZL12NumMoveToCpy", "NumMoveToCpy"),
	mu_demangle_test("_ZL11NumCpyToSet", "NumCpyToSet"),
	mu_demangle_test("_ZL14NumMemSetInfer", "NumMemSetInfer"),
	mu_demangle_test("_ZL10NumChanged", "NumChanged"),
	mu_demangle_test("_ZL10NumAnnihil", "NumAnnihil"),
	mu_demangle_test("_ZL9NumFactor", "NumFactor"),
	mu_demangle_test("_ZL9NumLinear", "NumLinear"),
	mu_demangle_test("_ZL16IPNumGlobalConst", "IPNumGlobalConst"),
	mu_demangle_test("_ZL16IPNumInstRemoved", "IPNumInstRemoved"),
	mu_demangle_test("_ZL14NumInstRemoved", "NumInstRemoved"),
	mu_demangle_test("_ZL13NumDeadBlocks", "NumDeadBlocks"),
	mu_demangle_test("_ZL15IPNumArgsElimed", "IPNumArgsElimed"),
	mu_demangle_test("_ZL12NumConverted", "NumConverted"),
	mu_demangle_test("_ZL11NumReplaced", "NumReplaced"),
	mu_demangle_test("_ZL10NumGlobals", "NumGlobals"),
	mu_demangle_test("_ZL11NumPromoted", "NumPromoted"),
	mu_demangle_test("_ZL11NumAdjusted", "NumAdjusted"),
	mu_demangle_test("_ZL8NumSimpl", "NumSimpl"),
	mu_demangle_test("_ZL13NumSimplified", "NumSimplified"),
	mu_demangle_test("_ZL12NumAnnotated", "NumAnnotated"),
	mu_demangle_test("_ZL11NumRetDuped", "NumRetDuped"),
	mu_demangle_test("_ZL13NumEliminated", "NumEliminated"),
	mu_demangle_test("_ZL13NumAccumAdded", "NumAccumAdded"),
	mu_demangle_test("_ZL12NumDeadStore", "NumDeadStore"),
	mu_demangle_test("_ZL11NumCombined", "NumCombined"),
	mu_demangle_test("_ZL11NumSunkInst", "NumSunkInst"),
	mu_demangle_test("_ZL12NumConstProp", "NumConstProp"),
	mu_demangle_test("_ZL11NumDeadInst", "NumDeadInst"),
	mu_demangle_test("_ZL9NumExpand", "NumExpand"),
	mu_demangle_test("_ZL9NumFactor", "NumFactor"),
	mu_demangle_test("_ZL10NumReassoc", "NumReassoc"),
	mu_demangle_test("_ZL9NumBroken", "NumBroken"),
	mu_demangle_test("_ZL8NumLCSSA", "NumLCSSA"),
	mu_demangle_test("_ZL9NumNested", "NumNested"),
	mu_demangle_test("_ZL11NumInserted", "NumInserted"),
	mu_demangle_test("_ZL11NumUnrolled", "NumUnrolled"),
	mu_demangle_test("_ZL21NumCompletelyUnrolled", "NumCompletelyUnrolled"),
	mu_demangle_test("_ZL10NumUnwinds", "NumUnwinds"),
	mu_demangle_test("_ZL10NumInvokes", "NumInvokes"),
	mu_demangle_test("_ZL10NumSpilled", "NumSpilled"),
	mu_demangle_test("_ZL12NumPHIInsert", "NumPHIInsert"),
	mu_demangle_test("_ZL16NumLocalPromoted", "NumLocalPromoted"),
	mu_demangle_test("_ZL14NumSingleStore", "NumSingleStore"),
	mu_demangle_test("_ZL13NumDeadAlloca", "NumDeadAlloca"),
	mu_demangle_test("_ZL15NumSpeculations", "NumSpeculations"),
	mu_demangle_test("_ZL16MaxSCCIterations", "MaxSCCIterations"),
	mu_demangle_test("_ZL10NumReassoc", "NumReassoc"),
	mu_demangle_test("_ZL9NumFactor", "NumFactor"),
	mu_demangle_test("_ZL9NumExpand", "NumExpand"),
	mu_demangle_test("_ZL27NumCacheCompleteNonLocalPtr", "NumCacheCompleteNonLocalPtr"),
	mu_demangle_test("_ZL21NumUncacheNonLocalPtr", "NumUncacheNonLocalPtr"),
	mu_demangle_test("_ZL24NumCacheDirtyNonLocalPtr", "NumCacheDirtyNonLocalPtr"),
	mu_demangle_test("_ZL19NumCacheNonLocalPtr", "NumCacheNonLocalPtr"),
	mu_demangle_test("_ZL18NumUncacheNonLocal", "NumUncacheNonLocal"),
	mu_demangle_test("_ZL21NumCacheDirtyNonLocal", "NumCacheDirtyNonLocal"),
	mu_demangle_test("_ZL16NumCacheNonLocal", "NumCacheNonLocal"),
	mu_demangle_test("_ZL31NumBruteForceTripCountsComputed", "NumBruteForceTripCountsComputed"),
	mu_demangle_test("_ZL19NumArrayLenItCounts", "NumArrayLenItCounts"),
	mu_demangle_test("_ZL24NumTripCountsNotComputed", "NumTripCountsNotComputed"),
	mu_demangle_test("_ZL21NumTripCountsComputed", "NumTripCountsComputed"),
	mu_demangle_test("_ZN12_GLOBAL__N_15statsL15RelaxationStepsE", "(anonymous namespace)::stats::RelaxationSteps"),
	mu_demangle_test("_ZN12_GLOBAL__N_15statsL19RelaxedInstructionsE", "(anonymous namespace)::stats::RelaxedInstructions"),
	mu_demangle_test("_ZN12_GLOBAL__N_15statsL11ObjectBytesE", "(anonymous namespace)::stats::ObjectBytes"),
	mu_demangle_test("_ZN12_GLOBAL__N_15statsL16EmittedFragmentsE", "(anonymous namespace)::stats::EmittedFragments"),
	mu_demangle_test("_ZN12_GLOBAL__N_15statsL15FragmentLayoutsE", "(anonymous namespace)::stats::FragmentLayouts"),
	mu_demangle_test("_ZN12_GLOBAL__N_15statsL13EvaluateFixupE", "(anonymous namespace)::stats::EvaluateFixup"),
	mu_demangle_test("_ZN12_GLOBAL__N_15statsL14MCExprEvaluateE", "(anonymous namespace)::stats::MCExprEvaluate"),
	mu_demangle_test("_ZL11ProgramName", "ProgramName"),
	mu_demangle_test("_ZL20ActiveASTUnitObjects", "ActiveASTUnitObjects"),
	mu_demangle_test("_ZL12ConstEqIndex", "ConstEqIndex"),
	mu_demangle_test("_ZL15ConstNotEqIndex", "ConstNotEqIndex"),
	mu_demangle_test("_ZL11AutoRCIndex", "AutoRCIndex"),
	mu_demangle_test("_ZL11AutoRBIndex", "AutoRBIndex"),
	mu_demangle_test("_ZL20ConstraintRangeIndex", "ConstraintRangeIndex"),
	mu_demangle_test("_ZL12nAccessSpecs", "nAccessSpecs"),
	mu_demangle_test("_ZL7nBlocks", "nBlocks"),
	mu_demangle_test("_ZL14nFileScopeAsms", "nFileScopeAsms"),
	mu_demangle_test("_ZL8nFriends", "nFriends"),
	mu_demangle_test("_ZL16nFriendTemplates", "nFriendTemplates"),
	mu_demangle_test("_ZL13nLinkageSpecs", "nLinkageSpecs"),
	mu_demangle_test("_ZL11nNamespaces", "nNamespaces"),
	mu_demangle_test("_ZL16nNamespaceAliass", "nNamespaceAliass"),
	mu_demangle_test("_ZL21nObjCCompatibleAliass", "nObjCCompatibleAliass"),
	mu_demangle_test("_ZL14nObjCCategorys", "nObjCCategorys"),
	mu_demangle_test("_ZL18nObjCCategoryImpls", "nObjCCategoryImpls"),
	mu_demangle_test("_ZL20nObjCImplementations", "nObjCImplementations"),
	mu_demangle_test("_ZL15nObjCInterfaces", "nObjCInterfaces"),
	mu_demangle_test("_ZL14nObjCProtocols", "nObjCProtocols"),
	mu_demangle_test("_ZL12nObjCMethods", "nObjCMethods"),
	mu_demangle_test("_ZL14nObjCPropertys", "nObjCPropertys"),
	mu_demangle_test("_ZL15nClassTemplates", "nClassTemplates"),
	mu_demangle_test("_ZL18nFunctionTemplates", "nFunctionTemplates"),
	mu_demangle_test("_ZL22nTemplateTemplateParms", "nTemplateTemplateParms"),
	mu_demangle_test("_ZL6nEnums", "nEnums"),
	mu_demangle_test("_ZL8nRecords", "nRecords"),
	mu_demangle_test("_ZL11nCXXRecords", "nCXXRecords"),
	mu_demangle_test("_ZL29nClassTemplateSpecializations", "nClassTemplateSpecializations"),
	mu_demangle_test("_ZL36nClassTemplatePartialSpecializations", "nClassTemplatePartialSpecializations"),
	mu_demangle_test("_ZL18nTemplateTypeParms", "nTemplateTypeParms"),
	mu_demangle_test("_ZL9nTypedefs", "nTypedefs"),
	mu_demangle_test("_ZL25nUnresolvedUsingTypenames", "nUnresolvedUsingTypenames"),
	mu_demangle_test("_ZL7nUsings", "nUsings"),
	mu_demangle_test("_ZL16nUsingDirectives", "nUsingDirectives"),
	mu_demangle_test("_ZL13nUsingShadows", "nUsingShadows"),
	mu_demangle_test("_ZL7nFields", "nFields"),
	mu_demangle_test("_ZL17nObjCAtDefsFields", "nObjCAtDefsFields"),
	mu_demangle_test("_ZL10nObjCIvars", "nObjCIvars"),
	mu_demangle_test("_ZL10nFunctions", "nFunctions"),
	mu_demangle_test("_ZL11nCXXMethods", "nCXXMethods"),
	mu_demangle_test("_ZL16nCXXConstructors", "nCXXConstructors"),
	mu_demangle_test("_ZL15nCXXConversions", "nCXXConversions"),
	mu_demangle_test("_ZL15nCXXDestructors", "nCXXDestructors"),
	mu_demangle_test("_ZL21nNonTypeTemplateParms", "nNonTypeTemplateParms"),
	mu_demangle_test("_ZL5nVars", "nVars"),
	mu_demangle_test("_ZL15nImplicitParams", "nImplicitParams"),
	mu_demangle_test("_ZL9nParmVars", "nParmVars"),
	mu_demangle_test("_ZL14nEnumConstants", "nEnumConstants"),
	mu_demangle_test("_ZL15nIndirectFields", "nIndirectFields"),
	mu_demangle_test("_ZL22nUnresolvedUsingValues", "nUnresolvedUsingValues"),
	mu_demangle_test("_ZL11nObjCClasss", "nObjCClasss"),
	mu_demangle_test("_ZL21nObjCForwardProtocols", "nObjCForwardProtocols"),
	mu_demangle_test("_ZL18nObjCPropertyImpls", "nObjCPropertyImpls"),
	mu_demangle_test("_ZL14nStaticAsserts", "nStaticAsserts"),
	mu_demangle_test("_ZL17nTranslationUnits", "nTranslationUnits"),
	mu_demangle_test("_ZL13StmtClassInfo", "StmtClassInfo"),
	mu_demangle_test("_ZL11InlineLimit", "InlineLimit"),
	mu_demangle_test("_ZL13HintThreshold", "HintThreshold"),
	mu_demangle_test("_ZL13Disable256Bit", "Disable256Bit"),
	mu_demangle_test("_ZL8NoFusing", "NoFusing"),
	mu_demangle_test("_ZL17PrintFailedFusing", "PrintFailedFusing"),
	mu_demangle_test("_ZL16ReMatPICStubLoad", "ReMatPICStubLoad"),
	mu_demangle_test("_ZL19JITCompilerFunction", "JITCompilerFunction"),
	mu_demangle_test("_ZL15AsmWriterFlavor", "AsmWriterFlavor"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L6CCRVTsE", "llvm::(anonymous namespace)::CCRVTs"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L14CONTROL_REGVTsE", "llvm::(anonymous namespace)::CONTROL_REGVTs"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12DEBUG_REGVTsE", "llvm::(anonymous namespace)::DEBUG_REGVTs"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L7FR32VTsE", "llvm::(anonymous namespace)::FR32VTs"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L7FR64VTsE", "llvm::(anonymous namespace)::FR64VTs"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L7GR16VTsE", "llvm::(anonymous namespace)::GR16VTs"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12GR16_ABCDVTsE", "llvm::(anonymous namespace)::GR16_ABCDVTs"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L13GR16_NOREXVTsE", "llvm::(anonymous namespace)::GR16_NOREXVTs"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L7GR32VTsE", "llvm::(anonymous namespace)::GR32VTs"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12GR32_ABCDVTsE", "llvm::(anonymous namespace)::GR32_ABCDVTs"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L10GR32_ADVTsE", "llvm::(anonymous namespace)::GR32_ADVTs"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L13GR32_NOREXVTsE", "llvm::(anonymous namespace)::GR32_NOREXVTs"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12GR32_NOSPVTsE", "llvm::(anonymous namespace)::GR32_NOSPVTs"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L10GR32_TCVTsE", "llvm::(anonymous namespace)::GR32_TCVTs"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L7GR64VTsE", "llvm::(anonymous namespace)::GR64VTs"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12GR64_ABCDVTsE", "llvm::(anonymous namespace)::GR64_ABCDVTs"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L13GR64_NOREXVTsE", "llvm::(anonymous namespace)::GR64_NOREXVTs"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L18GR64_NOREX_NOSPVTsE", "llvm::(anonymous namespace)::GR64_NOREX_NOSPVTs"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12GR64_NOSPVTsE", "llvm::(anonymous namespace)::GR64_NOSPVTs"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L10GR64_TCVTsE", "llvm::(anonymous namespace)::GR64_TCVTs"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L13GR64_TCW64VTsE", "llvm::(anonymous namespace)::GR64_TCW64VTs"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L6GR8VTsE", "llvm::(anonymous namespace)::GR8VTs"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L13GR8_ABCD_HVTsE", "llvm::(anonymous namespace)::GR8_ABCD_HVTs"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L13GR8_ABCD_LVTsE", "llvm::(anonymous namespace)::GR8_ABCD_LVTs"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12GR8_NOREXVTsE", "llvm::(anonymous namespace)::GR8_NOREXVTs"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L8RFP32VTsE", "llvm::(anonymous namespace)::RFP32VTs"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L8RFP64VTsE", "llvm::(anonymous namespace)::RFP64VTs"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L8RFP80VTsE", "llvm::(anonymous namespace)::RFP80VTs"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L6RSTVTsE", "llvm::(anonymous namespace)::RSTVTs"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L14SEGMENT_REGVTsE", "llvm::(anonymous namespace)::SEGMENT_REGVTs"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L8VR128VTsE", "llvm::(anonymous namespace)::VR128VTs"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L8VR256VTsE", "llvm::(anonymous namespace)::VR256VTs"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L7VR64VTsE", "llvm::(anonymous namespace)::VR64VTs"),
	mu_demangle_test("_ZL14EnableARM3Addr", "EnableARM3Addr"),
	mu_demangle_test("_ZL20ForceAllBaseRegAlloc", "ForceAllBaseRegAlloc"),
	mu_demangle_test("_ZL21EnableLocalStackAlloc", "EnableLocalStackAlloc"),
	mu_demangle_test("_ZL17EnableBasePointer", "EnableBasePointer"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L6CCRVTsE", "llvm::(anonymous namespace)::CCRVTs"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L6DPRVTsE", "llvm::(anonymous namespace)::DPRVTs"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L8DPR_8VTsE", "llvm::(anonymous namespace)::DPR_8VTs"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L11DPR_VFP2VTsE", "llvm::(anonymous namespace)::DPR_VFP2VTs"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L6GPRVTsE", "llvm::(anonymous namespace)::GPRVTs"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L6QPRVTsE", "llvm::(anonymous namespace)::QPRVTs"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L8QPR_8VTsE", "llvm::(anonymous namespace)::QPR_8VTs"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L11QPR_VFP2VTsE", "llvm::(anonymous namespace)::QPR_VFP2VTs"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L7QQPRVTsE", "llvm::(anonymous namespace)::QQPRVTs"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12QQPR_VFP2VTsE", "llvm::(anonymous namespace)::QQPR_VFP2VTs"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L9QQQQPRVTsE", "llvm::(anonymous namespace)::QQQQPRVTs"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L6SPRVTsE", "llvm::(anonymous namespace)::SPRVTs"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L8SPR_8VTsE", "llvm::(anonymous namespace)::SPR_8VTs"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L7rGPRVTsE", "llvm::(anonymous namespace)::rGPRVTs"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L7tGPRVTsE", "llvm::(anonymous namespace)::tGPRVTs"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L8tcGPRVTsE", "llvm::(anonymous namespace)::tcGPRVTs"),
	mu_demangle_test("_ZL21AdjustJumpTableBlocks", "AdjustJumpTableBlocks"),
	mu_demangle_test("_ZL18DisableARMFastISel", "DisableARMFastISel"),
	mu_demangle_test("_ZL16DisableShifterOp", "DisableShifterOp"),
	mu_demangle_test("_ZL15CheckVMLxHazard", "CheckVMLxHazard"),
	mu_demangle_test("_ZL18EnableARMTailCalls", "EnableARMTailCalls"),
	mu_demangle_test("_ZL15ARMInterworking", "ARMInterworking"),
	mu_demangle_test("_ZL19JITCompilerFunction", "JITCompilerFunction"),
	mu_demangle_test("_ZL9ReserveR9", "ReserveR9"),
	mu_demangle_test("_ZL13DarwinUseMOVT", "DarwinUseMOVT"),
	mu_demangle_test("_ZL11StrictAlign", "StrictAlign"),
	mu_demangle_test("_ZL9ExpandMLx", "ExpandMLx"),
	mu_demangle_test("_ZL11ForceExapnd", "ForceExapnd"),
	mu_demangle_test("_ZL11ExpandLimit", "ExpandLimit"),
	mu_demangle_test("_ZL10OldT2IfCvt", "OldT2IfCvt"),
	mu_demangle_test("_ZL11ReduceLimit", "ReduceLimit"),
	mu_demangle_test("_ZL16ReduceLimit2Addr", "ReduceLimit2Addr"),
	mu_demangle_test("_ZL15ReduceLimitLdSt", "ReduceLimitLdSt"),
	mu_demangle_test("_ZN12_GLOBAL__N_1L10CombinerAAE", "(anonymous namespace)::CombinerAA"),
	mu_demangle_test("_ZN12_GLOBAL__N_1L16CombinerGlobalAAE", "(anonymous namespace)::CombinerGlobalAA"),
	mu_demangle_test("_ZL21EnableExpensiveChecks", "EnableExpensiveChecks"),
	mu_demangle_test("_ZL18tdListDAGScheduler", "tdListDAGScheduler"),
	mu_demangle_test("_ZL20burrListDAGScheduler", "burrListDAGScheduler"),
	mu_demangle_test("_ZL20tdrListrDAGScheduler", "tdrListrDAGScheduler"),
	mu_demangle_test("_ZL22sourceListDAGScheduler", "sourceListDAGScheduler"),
	mu_demangle_test("_ZL22hybridListDAGScheduler", "hybridListDAGScheduler"),
	mu_demangle_test("_ZL19ILPListDAGScheduler", "ILPListDAGScheduler"),
	mu_demangle_test("_ZL18DisableSchedCycles", "DisableSchedCycles"),
	mu_demangle_test("_ZL4EVTs", "EVTs"),
	mu_demangle_test("_ZL13SimpleVTArray", "SimpleVTArray"),
	mu_demangle_test("_ZL7VTMutex", "VTMutex"),
	mu_demangle_test("_ZL16LimitFPPrecision", "LimitFPPrecision"),
	mu_demangle_test("_ZL19LimitFloatPrecision", "LimitFloatPrecision"),
	mu_demangle_test("_ZL17MaxParallelChains", "MaxParallelChains"),
	mu_demangle_test("_ZL21EnableFastISelVerbose", "EnableFastISelVerbose"),
	mu_demangle_test("_ZL19EnableFastISelAbort", "EnableFastISelAbort"),
	mu_demangle_test("_ZL11ISHeuristic", "ISHeuristic"),
	mu_demangle_test("_ZL23defaultListDAGScheduler", "defaultListDAGScheduler"),
	mu_demangle_test("_ZL13PrintDbgScope", "PrintDbgScope"),
	mu_demangle_test("_ZL24DisableDebugInfoPrinting", "DisableDebugInfoPrinting"),
	mu_demangle_test("_ZL16UnknownLocations", "UnknownLocations"),
	mu_demangle_test("_ZL8DebugDiv", "DebugDiv"),
	mu_demangle_test("_ZL8DebugMod", "DebugMod"),
	mu_demangle_test("_ZL19FlagEnableTailMerge", "FlagEnableTailMerge"),
	mu_demangle_test("_ZL18TailMergeThreshold", "TailMergeThreshold"),
	mu_demangle_test("_ZL13TailMergeSize", "TailMergeSize"),
	mu_demangle_test("_ZL15ViewEdgeBundles", "ViewEdgeBundles"),
	mu_demangle_test("_ZL12IfCvtFnStart", "IfCvtFnStart"),
	mu_demangle_test("_ZL11IfCvtFnStop", "IfCvtFnStop"),
	mu_demangle_test("_ZL10IfCvtLimit", "IfCvtLimit"),
	mu_demangle_test("_ZL13DisableSimple", "DisableSimple"),
	mu_demangle_test("_ZL14DisableSimpleF", "DisableSimpleF"),
	mu_demangle_test("_ZL15DisableTriangle", "DisableTriangle"),
	mu_demangle_test("_ZL16DisableTriangleR", "DisableTriangleR"),
	mu_demangle_test("_ZL16DisableTriangleF", "DisableTriangleF"),
	mu_demangle_test("_ZL17DisableTriangleFR", "DisableTriangleFR"),
	mu_demangle_test("_ZL14DisableDiamond", "DisableDiamond"),
	mu_demangle_test("_ZL15IfCvtBranchFold", "IfCvtBranchFold"),
	mu_demangle_test("_ZL12VerifySpills", "VerifySpills"),
	mu_demangle_test("_ZL13DisablePostRA", "DisablePostRA"),
	mu_demangle_test("_ZL17DisableBranchFold", "DisableBranchFold"),
	mu_demangle_test("_ZL20DisableTailDuplicate", "DisableTailDuplicate"),
	mu_demangle_test("_ZL19DisableEarlyTailDup", "DisableEarlyTailDup"),
	mu_demangle_test("_ZL16DisableCodePlace", "DisableCodePlace"),
	mu_demangle_test("_ZL10DisableSSC", "DisableSSC"),
	mu_demangle_test("_ZL18DisableMachineLICM", "DisableMachineLICM"),
	mu_demangle_test("_ZL24DisablePostRAMachineLICM", "DisablePostRAMachineLICM"),
	mu_demangle_test("_ZL18DisableMachineSink", "DisableMachineSink"),
	mu_demangle_test("_ZL10DisableLSR", "DisableLSR"),
	mu_demangle_test("_ZL10DisableCGP", "DisableCGP"),
	mu_demangle_test("_ZL8PrintLSR", "PrintLSR"),
	mu_demangle_test("_ZL14PrintISelInput", "PrintISelInput"),
	mu_demangle_test("_ZL11PrintGCInfo", "PrintGCInfo"),
	mu_demangle_test("_ZL14ShowMCEncoding", "ShowMCEncoding"),
	mu_demangle_test("_ZL10ShowMCInst", "ShowMCInst"),
	mu_demangle_test("_ZL15EnableMCLogging", "EnableMCLogging"),
	mu_demangle_test("_ZL17VerifyMachineCode", "VerifyMachineCode"),
	mu_demangle_test("_ZL10AsmVerbose", "AsmVerbose"),
	mu_demangle_test("_ZL20EnableFastISelOption", "EnableFastISelOption"),
	mu_demangle_test("_ZL17EnableSplitGEPGVN", "EnableSplitGEPGVN"),
	mu_demangle_test("_ZL9EnableLDV", "EnableLDV"),
	mu_demangle_test("_ZL12DisableReMat", "DisableReMat"),
	mu_demangle_test("_ZL10SplitEdges", "SplitEdges"),
	mu_demangle_test("_ZL15defaultRegAlloc", "defaultRegAlloc"),
	mu_demangle_test("_ZL8RegAlloc", "RegAlloc"),
	mu_demangle_test("_ZL10Aggressive", "Aggressive"),
	mu_demangle_test("_ZL15DisablePeephole", "DisablePeephole"),
	mu_demangle_test("_ZL21EnablePostRAScheduler", "EnablePostRAScheduler"),
	mu_demangle_test("_ZL21EnableAntiDepBreaking", "EnableAntiDepBreaking"),
	mu_demangle_test("_ZL8DebugDiv", "DebugDiv"),
	mu_demangle_test("_ZL8DebugMod", "DebugMod"),
	mu_demangle_test("_ZL13PreSplitLimit", "PreSplitLimit"),
	mu_demangle_test("_ZL14DeadSplitLimit", "DeadSplitLimit"),
	mu_demangle_test("_ZL16RestoreFoldLimit", "RestoreFoldLimit"),
	mu_demangle_test("_ZN12_GLOBAL__N_1L10PSVGlobalsE", "(anonymous namespace)::PSVGlobals"),
	mu_demangle_test("_ZL12fastRegAlloc", "fastRegAlloc"),
	mu_demangle_test("_ZL12NewHeuristic", "NewHeuristic"),
	mu_demangle_test("_ZL17PreSplitIntervals", "PreSplitIntervals"),
	mu_demangle_test("_ZL16TrivCoalesceEnds", "TrivCoalesceEnds"),
	mu_demangle_test("_ZL18linearscanRegAlloc", "linearscanRegAlloc"),
	mu_demangle_test("_ZN12_GLOBAL__N_1L19NumRecentlyUsedRegsE", "(anonymous namespace)::NumRecentlyUsedRegs"),
	mu_demangle_test("_ZL14ShrinkWrapping", "ShrinkWrapping"),
	mu_demangle_test("_ZL14ShrinkWrapFunc", "ShrinkWrapFunc"),
	mu_demangle_test("_ZL19ShrinkWrapDebugging", "ShrinkWrapDebugging"),
	mu_demangle_test("_ZL13EnableJoining", "EnableJoining"),
	mu_demangle_test("_ZL21DisableCrossClassJoin", "DisableCrossClassJoin"),
	mu_demangle_test("_ZL19DisablePhysicalJoin", "DisablePhysicalJoin"),
	mu_demangle_test("_ZL16VerifyCoalescing", "VerifyCoalescing"),
	mu_demangle_test("_ZL10spillerOpt", "spillerOpt"),
	mu_demangle_test("_ZL13SSPBufferSize", "SSPBufferSize"),
	mu_demangle_test("_ZL14DisableSharing", "DisableSharing"),
	mu_demangle_test("_ZL16ColorWithRegsOpt", "ColorWithRegsOpt"),
	mu_demangle_test("_ZL8DCELimit", "DCELimit"),
	mu_demangle_test("_ZL17TailDuplicateSize", "TailDuplicateSize"),
	mu_demangle_test("_ZL13TailDupVerify", "TailDupVerify"),
	mu_demangle_test("_ZL12TailDupLimit", "TailDupLimit"),
	mu_demangle_test("_ZL23DisableHazardRecognizer", "DisableHazardRecognizer"),
	mu_demangle_test("_ZL11RewriterOpt", "RewriterOpt"),
	mu_demangle_test("_ZL14ScheduleSpills", "ScheduleSpills"),
	mu_demangle_test("_ZL17CriticalEdgeSplit", "CriticalEdgeSplit"),
	mu_demangle_test("_ZL9EnablePRE", "EnablePRE"),
	mu_demangle_test("_ZL13EnableLoadPRE", "EnableLoadPRE"),
	mu_demangle_test("_ZL9Threshold", "Threshold"),
	mu_demangle_test("_ZL16DisablePromotion", "DisablePromotion"),
	mu_demangle_test("_ZL15UnrollThreshold", "UnrollThreshold"),
	mu_demangle_test("_ZL11UnrollCount", "UnrollCount"),
	mu_demangle_test("_ZL18UnrollAllowPartial", "UnrollAllowPartial"),
	mu_demangle_test("_ZL9Threshold", "Threshold"),
	mu_demangle_test("_ZL18ExpensiveEHSupport", "ExpensiveEHSupport"),
	mu_demangle_test("_ZL6DupRet", "DupRet"),
	mu_demangle_test("_ZL13MaxIterations", "MaxIterations"),
	mu_demangle_test("_ZL14VerifyLoopInfo", "VerifyLoopInfo"),
	mu_demangle_test("_ZL15VerifyLoopInfoX", "VerifyLoopInfoX"),
	mu_demangle_test("_ZL23MaxBruteForceIterations", "MaxBruteForceIterations"),
	mu_demangle_test("_ZL10EnableTBAA", "EnableTBAA"),
	mu_demangle_test("_ZL9PrintCode", "PrintCode"),
	mu_demangle_test("_ZL13DisableFPElim", "DisableFPElim"),
	mu_demangle_test("_ZL20DisableFPElimNonLeaf", "DisableFPElimNonLeaf"),
	mu_demangle_test("_ZL22DisableExcessPrecision", "DisableExcessPrecision"),
	mu_demangle_test("_ZL11EnableFPMAD", "EnableFPMAD"),
	mu_demangle_test("_ZL18EnableUnsafeFPMath", "EnableUnsafeFPMath"),
	mu_demangle_test("_ZL18EnableNoInfsFPMath", "EnableNoInfsFPMath"),
	mu_demangle_test("_ZL18EnableNoNaNsFPMath", "EnableNoNaNsFPMath"),
	mu_demangle_test("_ZL38EnableHonorSignDependentRoundingFPMath", "EnableHonorSignDependentRoundingFPMath"),
	mu_demangle_test("_ZL22GenerateSoftFloatCalls", "GenerateSoftFloatCalls"),
	mu_demangle_test("_ZL16FloatABIForCalls", "FloatABIForCalls"),
	mu_demangle_test("_ZL19DontPlaceZerosInBSS", "DontPlaceZerosInBSS"),
	mu_demangle_test("_ZL26EnableJITExceptionHandling", "EnableJITExceptionHandling"),
	mu_demangle_test("_ZL16EmitJitDebugInfo", "EmitJitDebugInfo"),
	mu_demangle_test("_ZL22EmitJitDebugInfoToDisk", "EmitJitDebugInfoToDisk"),
	mu_demangle_test("_ZL18EnableUnwindTables", "EnableUnwindTables"),
	mu_demangle_test("_ZL18DefRelocationModel", "DefRelocationModel"),
	mu_demangle_test("_ZL12DefCodeModel", "DefCodeModel"),
	mu_demangle_test("_ZL27EnableGuaranteedTailCallOpt", "EnableGuaranteedTailCallOpt"),
	mu_demangle_test("_ZL22OverrideStackAlignment", "OverrideStackAlignment"),
	mu_demangle_test("_ZL18EnableRealignStack", "EnableRealignStack"),
	mu_demangle_test("_ZL19DisableSwitchTables", "DisableSwitchTables"),
	mu_demangle_test("_ZL19EnableStrongPHIElim", "EnableStrongPHIElim"),
	mu_demangle_test("_ZL12DataSections", "DataSections"),
	mu_demangle_test("_ZL16FunctionSections", "FunctionSections"),
	mu_demangle_test("_ZL15AttributesLists", "AttributesLists"),
	mu_demangle_test("_ZN4llvmL7ALMutexE", "llvm::ALMutex"),
	mu_demangle_test("_ZL13VerifyDomInfo", "VerifyDomInfo"),
	mu_demangle_test("_ZL14VerifyDomInfoX", "VerifyDomInfoX"),
	mu_demangle_test("_ZL6GCLock", "GCLock"),
	mu_demangle_test("_ZL7GCNames", "GCNames"),
	mu_demangle_test("_ZL10GCNamePool", "GCNamePool"),
	mu_demangle_test("_ZL13GlobalContext", "GlobalContext"),
	mu_demangle_test("_ZN4llvmL13PassDebuggingE", "llvm::PassDebugging"),
	mu_demangle_test("_ZN4llvmL11PrintBeforeE", "llvm::PrintBefore"),
	mu_demangle_test("_ZN4llvmL10PrintAfterE", "llvm::PrintAfter"),
	mu_demangle_test("_ZN4llvmL14PrintBeforeAllE", "llvm::PrintBeforeAll"),
	mu_demangle_test("_ZN4llvmL13PrintAfterAllE", "llvm::PrintAfterAll"),
	mu_demangle_test("_ZN12_GLOBAL__N_1L15TimingInfoMutexE", "(anonymous namespace)::TimingInfoMutex"),
	mu_demangle_test("_ZL12EnableTiming", "EnableTiming"),
	mu_demangle_test("_ZL11TheTimeInfo", "TheTimeInfo"),
	mu_demangle_test("_ZL15PassRegistryObj", "PassRegistryObj"),
	mu_demangle_test("_ZL4Lock", "Lock"),
	mu_demangle_test("_ZL8MoreHelp", "MoreHelp"),
	mu_demangle_test("_ZL20RegisteredOptionList", "RegisteredOptionList"),
	mu_demangle_test("_ZL15ProgramOverview", "ProgramOverview"),
	mu_demangle_test("_ZL13NormalPrinter", "NormalPrinter"),
	mu_demangle_test("_ZL13HiddenPrinter", "HiddenPrinter"),
	mu_demangle_test("_ZL3HOp", "HOp"),
	mu_demangle_test("_ZL4HHOp", "HHOp"),
	mu_demangle_test("_ZL6VersOp", "VersOp"),
	mu_demangle_test("_ZL22VersionPrinterInstance", "VersionPrinterInstance"),
	mu_demangle_test("_ZL22OverrideVersionPrinter", "OverrideVersionPrinter"),
	mu_demangle_test("_ZN12_GLOBAL__N_1L14CurrentContextE", "(anonymous namespace)::CurrentContext"),
	mu_demangle_test("_ZL25gCrashRecoveryContexMutex", "gCrashRecoveryContexMutex"),
	mu_demangle_test("_ZL11PrevActions", "PrevActions"),
	mu_demangle_test("_ZL5Dummy", "Dummy"),
	mu_demangle_test("_ZL15ExplicitSymbols", "ExplicitSymbols"),
	mu_demangle_test("_ZL13OpenedHandles", "OpenedHandles"),
	mu_demangle_test("_ZL12ErrorHandler", "ErrorHandler"),
	mu_demangle_test("_ZL20ErrorHandlerUserData", "ErrorHandlerUserData"),
	mu_demangle_test("_ZL10StaticList", "StaticList"),
	mu_demangle_test("_ZN12_GLOBAL__N_1L7successE", "(anonymous namespace)::success"),
	mu_demangle_test("_ZN12_GLOBAL__N_1L10separatorsE", "(anonymous namespace)::separators"),
	mu_demangle_test("_ZN12_GLOBAL__N_1L7successE", "(anonymous namespace)::success"),
	mu_demangle_test("_ZL20PrettyStackTraceHead", "PrettyStackTraceHead"),
	mu_demangle_test("_ZL12SignalsMutex", "SignalsMutex"),
	mu_demangle_test("_ZL13FilesToRemove", "FilesToRemove"),
	mu_demangle_test("_ZL14CallBacksToRun", "CallBacksToRun"),
	mu_demangle_test("_ZL17InterruptFunction", "InterruptFunction"),
	mu_demangle_test("_ZL20NumRegisteredSignals", "NumRegisteredSignals"),
	mu_demangle_test("_ZL20RegisteredSignalInfo", "RegisteredSignalInfo"),
	mu_demangle_test("_ZL7Enabled", "Enabled"),
	mu_demangle_test("_ZL8StatInfo", "StatInfo"),
	mu_demangle_test("_ZL8StatLock", "StatLock"),
	mu_demangle_test("_ZL11FirstTarget", "FirstTarget"),
	mu_demangle_test("_ZL11global_lock", "global_lock"),
	mu_demangle_test("_ZL28LibSupportInfoOutputFilename", "LibSupportInfoOutputFilename"),
	mu_demangle_test("_ZL9TimerLock", "TimerLock"),
	mu_demangle_test("_ZN12_GLOBAL__N_1L10TrackSpaceE", "(anonymous namespace)::TrackSpace"),
	mu_demangle_test("_ZN12_GLOBAL__N_1L18InfoOutputFilenameE", "(anonymous namespace)::InfoOutputFilename"),
	mu_demangle_test("_ZL12ActiveTimers", "ActiveTimers"),
	mu_demangle_test("_ZL11NamedTimers", "NamedTimers"),
	mu_demangle_test("_ZL18NamedGroupedTimers", "NamedGroupedTimers"),
	mu_demangle_test("_ZL14TimerGroupList", "TimerGroupList"),
	mu_demangle_test("_ZL17DefaultTimerGroup", "DefaultTimerGroup"),
	mu_demangle_test("_ZL16NotUnderValgrind", "NotUnderValgrind"),
	mu_demangle_test("_ZN8Blizzard6Memory12voidp_returncvPT_IcEEv", "Blizzard::Memory::voidp_return::operator char*<char>()"),
	mu_demangle_test("_Z2f0PU3AS1c", "f0(char AS1*)"),
	mu_demangle_test("_ZN5Casts8implicitILj4EEEvPN9enable_ifIXstT_EvE4typeE", "void Casts::implicit<4u>(enable_if<sizeof (4u), void>::type*)"),
	mu_demangle_test("_ZN5Casts8implicitILj4EEEvPN9enable_ifIXszT_EvE4typeE", "void Casts::implicit<4u>(enable_if<sizeof (4u), void>::type*)"),
	mu_demangle_test("_ZN5Casts8implicitILj4EEEvPN9enable_ifIXatT_EvE4typeE", "void Casts::implicit<4u>(enable_if<alignof (4u), void>::type*)"),
	mu_demangle_test("_ZN5Casts8implicitILj4EEEvPN9enable_ifIXazT_EvE4typeE", "void Casts::implicit<4u>(enable_if<alignof (4u), void>::type*)"),
	mu_demangle_test("_Z1fPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP1XS13_S12_S11_S10_SZ_SY_SX_SW_SV_SU_ST_SS_SR_SQ_SP_SO_SN_SM_SL_SK_SJ_"
			 "SI_SH_SG_SF_SE_SD_SC_SB_SA_S9_S8_S7_S6_S5_S4_S3_S2_S1_S0_S_",
		"f(X****************************************, X****************************************, "
		"X***************************************, X**************************************, "
		"X*************************************, X************************************, "
		"X***********************************, X**********************************, X*********************************, "
		"X********************************, X*******************************, X******************************, "
		"X*****************************, X****************************, X***************************, "
		"X**************************, X*************************, X************************, X***********************, "
		"X**********************, X*********************, X********************, X*******************, "
		"X******************, X*****************, X****************, X***************, X**************, X*************, "
		"X************, X***********, X**********, X*********, X********, X*******, X******, X*****, X****, X***, X**, "
		"X*, X)"),
	mu_demangle_test("_ZZN1J1KEvENK1C1FEv", "J::K()::C::F() const"),
	mu_demangle_test("_ZZNVK1J1KEvENK1C1FEv", "J::K() const volatile::C::F() const"),
	mu_demangle_test("_Z1fM1AKFvvE", "f(void (A::*)() const)"),
	mu_demangle_test("_ZNR1X1fEv", "X::f() &"),
	mu_demangle_test("_ZNKO1X1hEv", "X::h() const &&"),
	//    mu_demangle_test("_Z1fM1XVKFivEMS_VFivEMS_KOFivE", "f(int (X::*)() const volatile, int (X::*)() volatile, int (X::*)() const &&)"),
	//    mu_demangle_test("_Z1fM1XRFivEMS_OFivEMS_KOFivE", "f(int (X::*)() &, int (X::*)() &&, int (X::*)() const &&)"),
	mu_demangle_test("_ZN5test12f0ENS_1TILZNS_1xEEEE", "test1::f0(test1::T<test1::x>)"),
	mu_demangle_test("_ZN5test12f1ENS_2t1ILZNS_2f0EfEEE", "test1::f1(test1::t1<test1::f0(float)>)"),
	mu_demangle_test("_ZN5test32f1ENS_2t1ILZ8test3_f0EEE", "test3::f1(test3::t1<test3_f0>)"),
	mu_demangle_test("_ZN5test42f1ENS_2t1IXadL_Z8test4_f0EEEE", "test4::f1(test4::t1<&test4_f0>)"),
	mu_demangle_test("_ZN5test52f1ENS_2t1ILZ8test5_f0EEE", "test5::f1(test5::t1<test5_f0>)"),
	mu_demangle_test("_ZN5test52f2ENS_2t2ILZ4mainEEE", "test5::f2(test5::t2<main>)"),
	mu_demangle_test("_ZN5test52f2ENS_2t2ILZ4mainEEE", "test5::f2(test5::t2<main>)"),
	mu_demangle_test("_ZN5test81fIiEEvNS_5int_cIXsrNS_4metaIT_E4typeE5valueEEE", "void test8::f<int>(test8::int_c<test8::meta<int>::type::value>)"),
	mu_demangle_test("_ZN5test91fIiNS_1XEEENS_9supermetaIT_E5applyIT0_E4typeEv", "test9::supermeta<int>::apply<test9::X>::type test9::f<int, test9::X>()"),
	mu_demangle_test("_ZN6test101fIidEENS_1XIT_E10definitionIT0_EES2_S5_", "test10::X<int>::definition<double> test10::f<int, double>(int, double)"),
	mu_demangle_test("_ZZ2f5vE1a", "f5()::a"),
	mu_demangle_test("_ZZ2f6vE1b", "f6()::b"),
	mu_demangle_test("_ZNV3$_35test9Ev", "$_3::test9() volatile"),
	mu_demangle_test("_ZN5Test8I3$_2EC1ES0_", "Test8<$_2>::Test8($_2)"),
	mu_demangle_test("_Z3fooIZN3BarC1EvE3$_0EvT_", "void foo<Bar::Bar()::$_0>(Bar::Bar()::$_0)"),
	mu_demangle_test("_ZGVZN1N1gEvE1a", "guard variable for N::g()::a"),
	mu_demangle_test("_ZplRK1YRA100_P1X", "operator+(Y const&, X* (&) [100])"),
	mu_demangle_test("_Z1fM1SKFvvE", "f(void (S::*)() const)"),
	mu_demangle_test("_Z3ft7IiEN11__enable_ifIXsr16__is_scalar_typeIT_EE7__valueEvE6__typeEv", "__enable_if<__is_scalar_type<int>::__value, void>::__type ft7<int>()"),
	mu_demangle_test("_Z3ft7IPvEN11__enable_ifIXsr16__is_scalar_typeIT_EE7__valueEvE6__typeEv", "__enable_if<__is_scalar_type<void*>::__value, void>::__type ft7<void*>()"),
	mu_demangle_test("_ZN6PR57968__fill_aIiEENS_11__enable_ifIXntsrNS_11__is_scalarIT_EE7__valueEvE6__typeEv", "PR5796::__enable_if<!PR5796::__is_scalar<int>::__value, void>::__type PR5796::__fill_a<int>()"),
	mu_demangle_test("_ZN3OpsplERKS_", "Ops::operator+(Ops const&)"),
	mu_demangle_test("_ZN5test01fIdEEvT_RAszcl3ovlcvS1__EE_c", "void test0::f<double>(double, char (&) [sizeof (ovl((double)()))])"),
	mu_demangle_test("_ZN5test01fIiEEvT_RAszcl3ovlcvS1__EE_c", "void test0::f<int>(int, char (&) [sizeof (ovl((int)()))])"),
	mu_demangle_test("_ZN5test01jINS_1AEEEvRAszdtcvT__E6buffer_c", "void test0::j<test0::A>(char (&) [sizeof (((test0::A)()).buffer)])"),
	mu_demangle_test("_ZN5test11fINS_1XEiEEvT_IT0_E", "void test1::f<test1::X, int>(test1::X<int>)"),
	mu_demangle_test("_ZN5test41gEPNS_3zedIXadL_ZNS_3foo3barEEEEE", "test4::g(test4::zed<&test4::foo::bar>*)"),
	mu_demangle_test("_ZN5test51gEPNS_3zedIXadL_ZNS_3foo3barEEEEE", "test5::g(test5::zed<&test5::foo::bar>*)"),
	mu_demangle_test("_ZN5test91fIiNS_3barEEEvRKNT0_3baz1XE", "void test9::f<int, test9::bar>(test9::bar::baz::X const&)"),
	mu_demangle_test("_ZN6test111fEz", "test11::f(...)"),
	mu_demangle_test("_ZN6test121fENS_1AILt33000EEE", "test12::f(test12::A<(unsigned short)33000>)"),
	mu_demangle_test("_ZN6test174funcINS_1BEEENS_1AIXszclsrT_3fooEEEEv", "test17::A<sizeof (test17::B::foo())> test17::func<test17::B>()"),
	mu_demangle_test("_ZN6test181fINS_1AEEEvNS_1SIXadsrT_plEEE", "void test18::f<test18::A>(test18::S<&test18::A::operator+>)"),
	mu_demangle_test("_ZN6test181fINS_1AEEEvNS_1SIXadsrT_anEEE", "void test18::f<test18::A>(test18::S<&test18::A::operator&>)"),
	mu_demangle_test("_ZN6test191gINS_1AEEEvNS_1SIXadsrT_plEEE", "void test19::g<test19::A>(test19::S<&test19::A::operator+>)"),
	mu_demangle_test("_ZN6test2112vla_arg_funcEiPA_i", "test21::vla_arg_func(int, int (*) [])"),
	mu_demangle_test("_ZN6test231fERA10_KPv", "test23::f(void* const (&) [10])"),
	mu_demangle_test("_ZN6test231fERA10_A5_VKPv", "test23::f(void* const volatile (&) [10][5])"),
	mu_demangle_test("_Z4testIcLj5ELj10ELj15EEvRAT0__AT1__AT2__T_", "void test<char, 5u, 10u, 15u>(char (&) [5u][10u][15u])"),
	mu_demangle_test("_Z2f1IJEEvv", "void f1<>()"),
	mu_demangle_test("_Z2f1IJiEEvv", "void f1<int>()"),
	mu_demangle_test("_Z2f1IJifEEvv", "void f1<int, float>()"),
	mu_demangle_test("_Z2f2IJEEvDpT_", "void f2<>()"),
	mu_demangle_test("_Z2f2IJiEEvDpT_", "void f2<int>(int)"),
	mu_demangle_test("_Z2f2IJifEEvDpT_", "void f2<int, float>(int, float)"),
	mu_demangle_test("_Z2f3IJEEvDpPKT_", "void f3<>()"),
	mu_demangle_test("_Z2f3IJiEEvDpPKT_", "void f3<int>(int const*)"),
	mu_demangle_test("_Z2f3IJifEEvDpPKT_", "void f3<int, float>(int const*, float const*)"),
	mu_demangle_test("_Z2f4IJifdEE5tupleIJDpT_EEv", "tuple<int, float, double> f4<int, float, double>()"),
	mu_demangle_test("_Z2f5IiJifdEE8identityIFT_DpT0_EEv", "identity<int (int, float, double)> f5<int, int, float, double>()"),
	mu_demangle_test("_Z2f6IJLi1ELi2ELi3EEE9int_tupleIJXspT_EEEv", "int_tuple<1, 2, 3> f6<1, 2, 3>()"),
	mu_demangle_test("_Z2f7IJ8identity13add_referenceEE14template_tupleIJDpT_EEv", "template_tuple<identity, add_reference> f7<identity, add_reference>()"),
	mu_demangle_test("_ZTC14SSDatabaseImpl0_N8Security10CssmClient6DbImplE", "construction vtable for Security::CssmClient::DbImpl-in-SSDatabaseImpl"),
	mu_demangle_test("_ZN7WebCore20createFileThreadTaskINS_15FileStreamProxyEN3WTF6StringERKS3_ddEENS2_10PassOwnPtrINS_10FileThread4TaskEEEPT_MSA_FvT1_T3_ERKT0_RKT2_", "WTF::PassOwnPtr<WebCore::FileThread::Task> WebCore::createFileThreadTask<WebCore::FileStreamProxy, WTF::String, WTF::String const&, double, double>(WebCore::FileStreamProxy*, void (WebCore::FileStreamProxy::*)(WTF::String const&, double), WTF::String const&, double const&)"),
	mu_demangle_test("_ZN2MF12_GLOBAL__N_114WeakCallHelperINS0_15DecodeQueueImplEEEvRKN5boost8functionIFvvEEERKNS3_8weak_ptrIT_EE", "void MF::(anonymous namespace)::WeakCallHelper<MF::(anonymous namespace)::DecodeQueueImpl>(boost::function<void ()> const&, boost::weak_ptr<MF::(anonymous namespace)::DecodeQueueImpl> const&)"),
	mu_demangle_test("_ZNK3com9markzware2js11cJSArgumentcvRKT_I8cMyClassEEv", "com::markzware::js::cJSArgument::operator cMyClass const&<cMyClass>() const"),
	mu_demangle_test("_Z1fIJicdEEPFvDpT_EPFvDpRPS0_ES8_S1_DpS4_S6_", "void (*f<int, char, double>(void (*)(int*&, char*&, double*&), void (*)(int*&, char*&, double*&), int, char, double, int*, char*, double*, int*&, char*&, double*&))(int, char, double)"),
	mu_demangle_test("_ZZ10+[Foo bar]E3Baz", "+[Foo bar]::Baz"),
	mu_demangle_test("_Z3fooPM2ABi", "foo(int AB::**)"),
	mu_demangle_test("_Z1rM1GFivEMS_KFivES_M1HFivES1_4whatIKS_E5what2IS8_ES3_", "r(int (G::*)(), int (G::*)() const, G, int (H::*)(), int (G::*)(), what<G const>, what2<G const>, int (G::*)() const)"),
	// INCORRECT : 	mu_demangle_test("_ZNK3Ncr6Silver7Utility6detail12CallOnThreadIZ53-[DeploymentSetupController handleManualServerEntry:]E3$_5EclIJEEEDTclclL_ZNS2_4getTIS4_EERT_vEEspclsr3stdE7forwardIT_Efp_EEEDpOSA_", "decltype(-[DeploymentSetupController handleManualServerEntry:]::$_5& Ncr::Silver::Utility::detail::getT<-[DeploymentSetupController handleManualServerEntry:]::$_5>()()()) Ncr::Silver::Utility::detail::CallOnThread<-[DeploymentSetupController handleManualServerEntry:]::$_5>::operator()<>() const"),
	mu_demangle_test("_Zli2_xy", "operator\"\" _x(unsigned long long)"),
	mu_demangle_test("_Z1fIiEDcT_", "decltype(auto) f<int>(int)"),
	mu_demangle_test("_ZZ4testvEN1g3fooE5Point", "test()::g::foo(Point)"),
	mu_demangle_test("_ZThn12_NSt9strstreamD0Ev", "non-virtual thunk to std::strstream::~strstream()"),
	mu_demangle_test("_ZTv0_n12_NSt9strstreamD0Ev", "virtual thunk to std::strstream::~strstream()"),
	// NOTE: disable this test since it is a negative test case, you cannot demangle a non-mangled symbol
	// mu_demangle_test("\x6D", nullptr), 	// This use to crash with ASAN
	mu_demangle_test("_ZTIU4_farrVKPi", "typeinfo for int* const volatile restrict _far"),
	// mangled names can include type manglings too, which don't start with _Z:
	// attribute abi_tag
	mu_demangle_test("_Z1fB3foov", "f[abi:foo]()"), );
mu_main(gpl, cxx, RZ_DEMANGLE_OPT_ENABLE_ALL);
