// SPDX-FileCopyrightText: 2021-2023 deroad <wargio@libero.it>
// SPDX-License-Identifier: LGPL-3.0-only

#include "minunit.h"

mu_demangle_tests(gpl,

	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12FP3_OverlapsE", "llvm::(anonymous namespace)::FP3_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12FP4_OverlapsE", "llvm::(anonymous namespace)::FP4_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12FP5_OverlapsE", "llvm::(anonymous namespace)::FP5_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12FP6_OverlapsE", "llvm::(anonymous namespace)::FP6_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L11FS_OverlapsE", "llvm::(anonymous namespace)::FS_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L11GS_OverlapsE", "llvm::(anonymous namespace)::GS_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L11IP_OverlapsE", "llvm::(anonymous namespace)::IP_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L15IP_SuperRegsSetE", "llvm::(anonymous namespace)::IP_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12MM0_OverlapsE", "llvm::(anonymous namespace)::MM0_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12MM1_OverlapsE", "llvm::(anonymous namespace)::MM1_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12MM2_OverlapsE", "llvm::(anonymous namespace)::MM2_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12MM3_OverlapsE", "llvm::(anonymous namespace)::MM3_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12MM4_OverlapsE", "llvm::(anonymous namespace)::MM4_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12MM5_OverlapsE", "llvm::(anonymous namespace)::MM5_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12MM6_OverlapsE", "llvm::(anonymous namespace)::MM6_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12MM7_OverlapsE", "llvm::(anonymous namespace)::MM7_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L11R8_OverlapsE", "llvm::(anonymous namespace)::R8_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L13R8_SubRegsSetE", "llvm::(anonymous namespace)::R8_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12R8B_OverlapsE", "llvm::(anonymous namespace)::R8B_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16R8B_SuperRegsSetE", "llvm::(anonymous namespace)::R8B_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12R8D_OverlapsE", "llvm::(anonymous namespace)::R8D_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L14R8D_SubRegsSetE", "llvm::(anonymous namespace)::R8D_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16R8D_SuperRegsSetE", "llvm::(anonymous namespace)::R8D_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12R8W_OverlapsE", "llvm::(anonymous namespace)::R8W_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L14R8W_SubRegsSetE", "llvm::(anonymous namespace)::R8W_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16R8W_SuperRegsSetE", "llvm::(anonymous namespace)::R8W_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L11R9_OverlapsE", "llvm::(anonymous namespace)::R9_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L13R9_SubRegsSetE", "llvm::(anonymous namespace)::R9_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12R9B_OverlapsE", "llvm::(anonymous namespace)::R9B_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16R9B_SuperRegsSetE", "llvm::(anonymous namespace)::R9B_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12R9D_OverlapsE", "llvm::(anonymous namespace)::R9D_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L14R9D_SubRegsSetE", "llvm::(anonymous namespace)::R9D_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16R9D_SuperRegsSetE", "llvm::(anonymous namespace)::R9D_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12R9W_OverlapsE", "llvm::(anonymous namespace)::R9W_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L14R9W_SubRegsSetE", "llvm::(anonymous namespace)::R9W_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16R9W_SuperRegsSetE", "llvm::(anonymous namespace)::R9W_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12R10_OverlapsE", "llvm::(anonymous namespace)::R10_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L14R10_SubRegsSetE", "llvm::(anonymous namespace)::R10_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L13R10B_OverlapsE", "llvm::(anonymous namespace)::R10B_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L17R10B_SuperRegsSetE", "llvm::(anonymous namespace)::R10B_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L13R10D_OverlapsE", "llvm::(anonymous namespace)::R10D_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L15R10D_SubRegsSetE", "llvm::(anonymous namespace)::R10D_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L17R10D_SuperRegsSetE", "llvm::(anonymous namespace)::R10D_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L13R10W_OverlapsE", "llvm::(anonymous namespace)::R10W_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L15R10W_SubRegsSetE", "llvm::(anonymous namespace)::R10W_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L17R10W_SuperRegsSetE", "llvm::(anonymous namespace)::R10W_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12R11_OverlapsE", "llvm::(anonymous namespace)::R11_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L14R11_SubRegsSetE", "llvm::(anonymous namespace)::R11_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L13R11B_OverlapsE", "llvm::(anonymous namespace)::R11B_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L17R11B_SuperRegsSetE", "llvm::(anonymous namespace)::R11B_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L13R11D_OverlapsE", "llvm::(anonymous namespace)::R11D_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L15R11D_SubRegsSetE", "llvm::(anonymous namespace)::R11D_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L17R11D_SuperRegsSetE", "llvm::(anonymous namespace)::R11D_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L13R11W_OverlapsE", "llvm::(anonymous namespace)::R11W_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L15R11W_SubRegsSetE", "llvm::(anonymous namespace)::R11W_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L17R11W_SuperRegsSetE", "llvm::(anonymous namespace)::R11W_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12R12_OverlapsE", "llvm::(anonymous namespace)::R12_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L14R12_SubRegsSetE", "llvm::(anonymous namespace)::R12_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L13R12B_OverlapsE", "llvm::(anonymous namespace)::R12B_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L17R12B_SuperRegsSetE", "llvm::(anonymous namespace)::R12B_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L13R12D_OverlapsE", "llvm::(anonymous namespace)::R12D_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L15R12D_SubRegsSetE", "llvm::(anonymous namespace)::R12D_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L17R12D_SuperRegsSetE", "llvm::(anonymous namespace)::R12D_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L13R12W_OverlapsE", "llvm::(anonymous namespace)::R12W_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L15R12W_SubRegsSetE", "llvm::(anonymous namespace)::R12W_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L17R12W_SuperRegsSetE", "llvm::(anonymous namespace)::R12W_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12R13_OverlapsE", "llvm::(anonymous namespace)::R13_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L14R13_SubRegsSetE", "llvm::(anonymous namespace)::R13_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L13R13B_OverlapsE", "llvm::(anonymous namespace)::R13B_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L17R13B_SuperRegsSetE", "llvm::(anonymous namespace)::R13B_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L13R13D_OverlapsE", "llvm::(anonymous namespace)::R13D_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L15R13D_SubRegsSetE", "llvm::(anonymous namespace)::R13D_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L17R13D_SuperRegsSetE", "llvm::(anonymous namespace)::R13D_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L13R13W_OverlapsE", "llvm::(anonymous namespace)::R13W_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L15R13W_SubRegsSetE", "llvm::(anonymous namespace)::R13W_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L17R13W_SuperRegsSetE", "llvm::(anonymous namespace)::R13W_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12R14_OverlapsE", "llvm::(anonymous namespace)::R14_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L14R14_SubRegsSetE", "llvm::(anonymous namespace)::R14_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L13R14B_OverlapsE", "llvm::(anonymous namespace)::R14B_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L17R14B_SuperRegsSetE", "llvm::(anonymous namespace)::R14B_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L13R14D_OverlapsE", "llvm::(anonymous namespace)::R14D_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L15R14D_SubRegsSetE", "llvm::(anonymous namespace)::R14D_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L17R14D_SuperRegsSetE", "llvm::(anonymous namespace)::R14D_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L13R14W_OverlapsE", "llvm::(anonymous namespace)::R14W_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L15R14W_SubRegsSetE", "llvm::(anonymous namespace)::R14W_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L17R14W_SuperRegsSetE", "llvm::(anonymous namespace)::R14W_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12R15_OverlapsE", "llvm::(anonymous namespace)::R15_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L14R15_SubRegsSetE", "llvm::(anonymous namespace)::R15_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L13R15B_OverlapsE", "llvm::(anonymous namespace)::R15B_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L17R15B_SuperRegsSetE", "llvm::(anonymous namespace)::R15B_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L13R15D_OverlapsE", "llvm::(anonymous namespace)::R15D_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L15R15D_SubRegsSetE", "llvm::(anonymous namespace)::R15D_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L17R15D_SuperRegsSetE", "llvm::(anonymous namespace)::R15D_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L13R15W_OverlapsE", "llvm::(anonymous namespace)::R15W_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L15R15W_SubRegsSetE", "llvm::(anonymous namespace)::R15W_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L17R15W_SuperRegsSetE", "llvm::(anonymous namespace)::R15W_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12RAX_OverlapsE", "llvm::(anonymous namespace)::RAX_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L14RAX_SubRegsSetE", "llvm::(anonymous namespace)::RAX_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12RBP_OverlapsE", "llvm::(anonymous namespace)::RBP_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L14RBP_SubRegsSetE", "llvm::(anonymous namespace)::RBP_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12RBX_OverlapsE", "llvm::(anonymous namespace)::RBX_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L14RBX_SubRegsSetE", "llvm::(anonymous namespace)::RBX_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12RCX_OverlapsE", "llvm::(anonymous namespace)::RCX_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L14RCX_SubRegsSetE", "llvm::(anonymous namespace)::RCX_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12RDI_OverlapsE", "llvm::(anonymous namespace)::RDI_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L14RDI_SubRegsSetE", "llvm::(anonymous namespace)::RDI_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12RDX_OverlapsE", "llvm::(anonymous namespace)::RDX_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L14RDX_SubRegsSetE", "llvm::(anonymous namespace)::RDX_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12RIP_OverlapsE", "llvm::(anonymous namespace)::RIP_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L14RIP_SubRegsSetE", "llvm::(anonymous namespace)::RIP_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12RIZ_OverlapsE", "llvm::(anonymous namespace)::RIZ_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12RSI_OverlapsE", "llvm::(anonymous namespace)::RSI_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L14RSI_SubRegsSetE", "llvm::(anonymous namespace)::RSI_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12RSP_OverlapsE", "llvm::(anonymous namespace)::RSP_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L14RSP_SubRegsSetE", "llvm::(anonymous namespace)::RSP_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L11SI_OverlapsE", "llvm::(anonymous namespace)::SI_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L13SI_SubRegsSetE", "llvm::(anonymous namespace)::SI_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L15SI_SuperRegsSetE", "llvm::(anonymous namespace)::SI_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12SIL_OverlapsE", "llvm::(anonymous namespace)::SIL_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16SIL_SuperRegsSetE", "llvm::(anonymous namespace)::SIL_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L11SP_OverlapsE", "llvm::(anonymous namespace)::SP_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L13SP_SubRegsSetE", "llvm::(anonymous namespace)::SP_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L15SP_SuperRegsSetE", "llvm::(anonymous namespace)::SP_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12SPL_OverlapsE", "llvm::(anonymous namespace)::SPL_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16SPL_SuperRegsSetE", "llvm::(anonymous namespace)::SPL_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L11SS_OverlapsE", "llvm::(anonymous namespace)::SS_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12ST0_OverlapsE", "llvm::(anonymous namespace)::ST0_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12ST1_OverlapsE", "llvm::(anonymous namespace)::ST1_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12ST2_OverlapsE", "llvm::(anonymous namespace)::ST2_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12ST3_OverlapsE", "llvm::(anonymous namespace)::ST3_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12ST4_OverlapsE", "llvm::(anonymous namespace)::ST4_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12ST5_OverlapsE", "llvm::(anonymous namespace)::ST5_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12ST6_OverlapsE", "llvm::(anonymous namespace)::ST6_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12ST7_OverlapsE", "llvm::(anonymous namespace)::ST7_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L13XMM0_OverlapsE", "llvm::(anonymous namespace)::XMM0_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L17XMM0_SuperRegsSetE", "llvm::(anonymous namespace)::XMM0_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L13XMM1_OverlapsE", "llvm::(anonymous namespace)::XMM1_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L17XMM1_SuperRegsSetE", "llvm::(anonymous namespace)::XMM1_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L13XMM2_OverlapsE", "llvm::(anonymous namespace)::XMM2_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L17XMM2_SuperRegsSetE", "llvm::(anonymous namespace)::XMM2_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L13XMM3_OverlapsE", "llvm::(anonymous namespace)::XMM3_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L17XMM3_SuperRegsSetE", "llvm::(anonymous namespace)::XMM3_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L13XMM4_OverlapsE", "llvm::(anonymous namespace)::XMM4_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L17XMM4_SuperRegsSetE", "llvm::(anonymous namespace)::XMM4_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L13XMM5_OverlapsE", "llvm::(anonymous namespace)::XMM5_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L17XMM5_SuperRegsSetE", "llvm::(anonymous namespace)::XMM5_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L13XMM6_OverlapsE", "llvm::(anonymous namespace)::XMM6_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L17XMM6_SuperRegsSetE", "llvm::(anonymous namespace)::XMM6_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L13XMM7_OverlapsE", "llvm::(anonymous namespace)::XMM7_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L17XMM7_SuperRegsSetE", "llvm::(anonymous namespace)::XMM7_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L13XMM8_OverlapsE", "llvm::(anonymous namespace)::XMM8_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L17XMM8_SuperRegsSetE", "llvm::(anonymous namespace)::XMM8_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L13XMM9_OverlapsE", "llvm::(anonymous namespace)::XMM9_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L17XMM9_SuperRegsSetE", "llvm::(anonymous namespace)::XMM9_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L14XMM10_OverlapsE", "llvm::(anonymous namespace)::XMM10_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L18XMM10_SuperRegsSetE", "llvm::(anonymous namespace)::XMM10_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L14XMM11_OverlapsE", "llvm::(anonymous namespace)::XMM11_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L18XMM11_SuperRegsSetE", "llvm::(anonymous namespace)::XMM11_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L14XMM12_OverlapsE", "llvm::(anonymous namespace)::XMM12_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L18XMM12_SuperRegsSetE", "llvm::(anonymous namespace)::XMM12_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L14XMM13_OverlapsE", "llvm::(anonymous namespace)::XMM13_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L18XMM13_SuperRegsSetE", "llvm::(anonymous namespace)::XMM13_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L14XMM14_OverlapsE", "llvm::(anonymous namespace)::XMM14_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L18XMM14_SuperRegsSetE", "llvm::(anonymous namespace)::XMM14_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L14XMM15_OverlapsE", "llvm::(anonymous namespace)::XMM15_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L18XMM15_SuperRegsSetE", "llvm::(anonymous namespace)::XMM15_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L13YMM0_OverlapsE", "llvm::(anonymous namespace)::YMM0_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L15YMM0_SubRegsSetE", "llvm::(anonymous namespace)::YMM0_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L13YMM1_OverlapsE", "llvm::(anonymous namespace)::YMM1_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L15YMM1_SubRegsSetE", "llvm::(anonymous namespace)::YMM1_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L13YMM2_OverlapsE", "llvm::(anonymous namespace)::YMM2_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L15YMM2_SubRegsSetE", "llvm::(anonymous namespace)::YMM2_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L13YMM3_OverlapsE", "llvm::(anonymous namespace)::YMM3_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L15YMM3_SubRegsSetE", "llvm::(anonymous namespace)::YMM3_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L13YMM4_OverlapsE", "llvm::(anonymous namespace)::YMM4_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L15YMM4_SubRegsSetE", "llvm::(anonymous namespace)::YMM4_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L13YMM5_OverlapsE", "llvm::(anonymous namespace)::YMM5_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L15YMM5_SubRegsSetE", "llvm::(anonymous namespace)::YMM5_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L13YMM6_OverlapsE", "llvm::(anonymous namespace)::YMM6_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L15YMM6_SubRegsSetE", "llvm::(anonymous namespace)::YMM6_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L13YMM7_OverlapsE", "llvm::(anonymous namespace)::YMM7_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L15YMM7_SubRegsSetE", "llvm::(anonymous namespace)::YMM7_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L13YMM8_OverlapsE", "llvm::(anonymous namespace)::YMM8_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L15YMM8_SubRegsSetE", "llvm::(anonymous namespace)::YMM8_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L13YMM9_OverlapsE", "llvm::(anonymous namespace)::YMM9_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L15YMM9_SubRegsSetE", "llvm::(anonymous namespace)::YMM9_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L14YMM10_OverlapsE", "llvm::(anonymous namespace)::YMM10_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16YMM10_SubRegsSetE", "llvm::(anonymous namespace)::YMM10_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L14YMM11_OverlapsE", "llvm::(anonymous namespace)::YMM11_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16YMM11_SubRegsSetE", "llvm::(anonymous namespace)::YMM11_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L14YMM12_OverlapsE", "llvm::(anonymous namespace)::YMM12_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16YMM12_SubRegsSetE", "llvm::(anonymous namespace)::YMM12_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L14YMM13_OverlapsE", "llvm::(anonymous namespace)::YMM13_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16YMM13_SubRegsSetE", "llvm::(anonymous namespace)::YMM13_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L14YMM14_OverlapsE", "llvm::(anonymous namespace)::YMM14_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16YMM14_SubRegsSetE", "llvm::(anonymous namespace)::YMM14_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L14YMM15_OverlapsE", "llvm::(anonymous namespace)::YMM15_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16YMM15_SubRegsSetE", "llvm::(anonymous namespace)::YMM15_SubRegsSet"),
	mu_demangle_test("_ZN4llvmL13ImplicitList1E", "llvm::ImplicitList1"),
	mu_demangle_test("_ZN4llvmL13ImplicitList2E", "llvm::ImplicitList2"),
	mu_demangle_test("_ZN4llvmL13ImplicitList3E", "llvm::ImplicitList3"),
	mu_demangle_test("_ZN4llvmL13ImplicitList4E", "llvm::ImplicitList4"),
	mu_demangle_test("_ZN4llvmL13ImplicitList5E", "llvm::ImplicitList5"),
	mu_demangle_test("_ZN4llvmL13ImplicitList6E", "llvm::ImplicitList6"),
	mu_demangle_test("_ZN4llvmL13ImplicitList7E", "llvm::ImplicitList7"),
	mu_demangle_test("_ZN4llvmL13ImplicitList8E", "llvm::ImplicitList8"),
	mu_demangle_test("_ZN4llvmL13ImplicitList9E", "llvm::ImplicitList9"),
	mu_demangle_test("_ZN4llvmL14ImplicitList10E", "llvm::ImplicitList10"),
	mu_demangle_test("_ZN4llvmL14ImplicitList11E", "llvm::ImplicitList11"),
	mu_demangle_test("_ZN4llvmL14ImplicitList12E", "llvm::ImplicitList12"),
	mu_demangle_test("_ZN4llvmL14ImplicitList13E", "llvm::ImplicitList13"),
	mu_demangle_test("_ZN4llvmL14ImplicitList14E", "llvm::ImplicitList14"),
	mu_demangle_test("_ZN4llvmL14ImplicitList15E", "llvm::ImplicitList15"),
	mu_demangle_test("_ZN4llvmL14ImplicitList16E", "llvm::ImplicitList16"),
	mu_demangle_test("_ZN4llvm3ARML18CCRSuperRegClassesE", "llvm::ARM::CCRSuperRegClasses"),
	mu_demangle_test("_ZN4llvm3ARML18GPRSuperRegClassesE", "llvm::ARM::GPRSuperRegClasses"),
	mu_demangle_test("_ZN4llvm3ARML20QPR_8SuperRegClassesE", "llvm::ARM::QPR_8SuperRegClasses"),
	mu_demangle_test("_ZN4llvm3ARML19QQPRSuperRegClassesE", "llvm::ARM::QQPRSuperRegClasses"),
	mu_demangle_test("_ZN4llvm3ARML24QQPR_VFP2SuperRegClassesE", "llvm::ARM::QQPR_VFP2SuperRegClasses"),
	mu_demangle_test("_ZN4llvm3ARML21QQQQPRSuperRegClassesE", "llvm::ARM::QQQQPRSuperRegClasses"),
	mu_demangle_test("_ZN4llvm3ARML19rGPRSuperRegClassesE", "llvm::ARM::rGPRSuperRegClasses"),
	mu_demangle_test("_ZN4llvm3ARML19tGPRSuperRegClassesE", "llvm::ARM::tGPRSuperRegClasses"),
	mu_demangle_test("_ZN4llvm3ARML20tcGPRSuperRegClassesE", "llvm::ARM::tcGPRSuperRegClasses"),
	mu_demangle_test("_ZN4llvm3ARML13CCRSubclassesE", "llvm::ARM::CCRSubclasses"),
	mu_demangle_test("_ZN4llvm3ARML15DPR_8SubclassesE", "llvm::ARM::DPR_8Subclasses"),
	mu_demangle_test("_ZN4llvm3ARML15QPR_8SubclassesE", "llvm::ARM::QPR_8Subclasses"),
	mu_demangle_test("_ZN4llvm3ARML19QQPR_VFP2SubclassesE", "llvm::ARM::QQPR_VFP2Subclasses"),
	mu_demangle_test("_ZN4llvm3ARML16QQQQPRSubclassesE", "llvm::ARM::QQQQPRSubclasses"),
	mu_demangle_test("_ZN4llvm3ARML15SPR_8SubclassesE", "llvm::ARM::SPR_8Subclasses"),
	mu_demangle_test("_ZN4llvm3ARML14tGPRSubclassesE", "llvm::ARM::tGPRSubclasses"),
	mu_demangle_test("_ZN4llvm3ARML15tcGPRSubclassesE", "llvm::ARM::tcGPRSubclasses"),
	mu_demangle_test("_ZN4llvm3ARML15CCRSuperclassesE", "llvm::ARM::CCRSuperclasses"),
	mu_demangle_test("_ZN4llvm3ARML15DPRSuperclassesE", "llvm::ARM::DPRSuperclasses"),
	mu_demangle_test("_ZN4llvm3ARML15GPRSuperclassesE", "llvm::ARM::GPRSuperclasses"),
	mu_demangle_test("_ZN4llvm3ARML15QPRSuperclassesE", "llvm::ARM::QPRSuperclasses"),
	mu_demangle_test("_ZN4llvm3ARML16QQPRSuperclassesE", "llvm::ARM::QQPRSuperclasses"),
	mu_demangle_test("_ZN4llvm3ARML18QQQQPRSuperclassesE", "llvm::ARM::QQQQPRSuperclasses"),
	mu_demangle_test("_ZN4llvm3ARML15SPRSuperclassesE", "llvm::ARM::SPRSuperclasses"),
	mu_demangle_test("_ZN4llvm3ARML16CCRSubRegClassesE", "llvm::ARM::CCRSubRegClasses"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L3CCRE", "llvm::(anonymous namespace)::CCR"),
	mu_demangle_test("_ZN4llvm3ARML12ARM_DPR_VFP3E", "llvm::ARM::ARM_DPR_VFP3"),
	mu_demangle_test("_ZN4llvm3ARML12ARM_DPR_VFP2E", "llvm::ARM::ARM_DPR_VFP2"),
	mu_demangle_test("_ZN4llvm3ARML16DPRSubRegClassesE", "llvm::ARM::DPRSubRegClasses"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L3DPRE", "llvm::(anonymous namespace)::DPR"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L5DPR_8E", "llvm::(anonymous namespace)::DPR_8"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L8DPR_VFP2E", "llvm::(anonymous namespace)::DPR_VFP2"),
	mu_demangle_test("_ZN4llvm3ARML12THUMB_GPR_AOE", "llvm::ARM::THUMB_GPR_AO"),
	mu_demangle_test("_ZN4llvm3ARML10ARM_GPR_AOE", "llvm::ARM::ARM_GPR_AO"),
	mu_demangle_test("_ZN4llvm3ARML16GPRSubRegClassesE", "llvm::ARM::GPRSubRegClasses"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L3GPRE", "llvm::(anonymous namespace)::GPR"),
	mu_demangle_test("_ZN4llvm3ARML7ARM_QPRE", "llvm::ARM::ARM_QPR"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L3QPRE", "llvm::(anonymous namespace)::QPR"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L5QPR_8E", "llvm::(anonymous namespace)::QPR_8"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L8QPR_VFP2E", "llvm::(anonymous namespace)::QPR_VFP2"),
	mu_demangle_test("_ZN4llvm3ARML8ARM_QQPRE", "llvm::ARM::ARM_QQPR"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L4QQPRE", "llvm::(anonymous namespace)::QQPR"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L9QQPR_VFP2E", "llvm::(anonymous namespace)::QQPR_VFP2"),
	mu_demangle_test("_ZN4llvm3ARML10ARM_QQQQPRE", "llvm::ARM::ARM_QQQQPR"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L6QQQQPRE", "llvm::(anonymous namespace)::QQQQPR"),
	mu_demangle_test("_ZN4llvm3ARML16SPRSubRegClassesE", "llvm::ARM::SPRSubRegClasses"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L3SPRE", "llvm::(anonymous namespace)::SPR"),
	mu_demangle_test("_ZN4llvm3ARML18SPR_8SubRegClassesE", "llvm::ARM::SPR_8SubRegClasses"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L5SPR_8E", "llvm::(anonymous namespace)::SPR_8"),
	mu_demangle_test("_ZN4llvm3ARML13THUMB_rGPR_AOE", "llvm::ARM::THUMB_rGPR_AO"),
	mu_demangle_test("_ZN4llvm3ARML11ARM_rGPR_AOE", "llvm::ARM::ARM_rGPR_AO"),
	mu_demangle_test("_ZN4llvm3ARML17rGPRSubRegClassesE", "llvm::ARM::rGPRSubRegClasses"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L4rGPRE", "llvm::(anonymous namespace)::rGPR"),
	mu_demangle_test("_ZN4llvm3ARML17tGPRSubRegClassesE", "llvm::ARM::tGPRSubRegClasses"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L4tGPRE", "llvm::(anonymous namespace)::tGPR"),
	mu_demangle_test("_ZN4llvm3ARML15THUMB_GPR_AO_TCE", "llvm::ARM::THUMB_GPR_AO_TC"),
	mu_demangle_test("_ZN4llvm3ARML13ARM_GPR_R9_TCE", "llvm::ARM::ARM_GPR_R9_TC"),
	mu_demangle_test("_ZN4llvm3ARML15ARM_GPR_NOR9_TCE", "llvm::ARM::ARM_GPR_NOR9_TC"),
	mu_demangle_test("_ZN4llvm3ARML18tcGPRSubRegClassesE", "llvm::ARM::tcGPRSubRegClasses"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L5tcGPRE", "llvm::(anonymous namespace)::tcGPR"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L15SubregHashTableE", "llvm::(anonymous namespace)::SubregHashTable"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16AliasesHashTableE", "llvm::(anonymous namespace)::AliasesHashTable"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L13CPSR_OverlapsE", "llvm::(anonymous namespace)::CPSR_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16Empty_SubRegsSetE", "llvm::(anonymous namespace)::Empty_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L18Empty_SuperRegsSetE", "llvm::(anonymous namespace)::Empty_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L11D0_OverlapsE", "llvm::(anonymous namespace)::D0_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L13D0_SubRegsSetE", "llvm::(anonymous namespace)::D0_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L15D0_SuperRegsSetE", "llvm::(anonymous namespace)::D0_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L11D1_OverlapsE", "llvm::(anonymous namespace)::D1_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L13D1_SubRegsSetE", "llvm::(anonymous namespace)::D1_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L15D1_SuperRegsSetE", "llvm::(anonymous namespace)::D1_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L11D2_OverlapsE", "llvm::(anonymous namespace)::D2_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L13D2_SubRegsSetE", "llvm::(anonymous namespace)::D2_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L15D2_SuperRegsSetE", "llvm::(anonymous namespace)::D2_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L11D3_OverlapsE", "llvm::(anonymous namespace)::D3_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L13D3_SubRegsSetE", "llvm::(anonymous namespace)::D3_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L15D3_SuperRegsSetE", "llvm::(anonymous namespace)::D3_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L11D4_OverlapsE", "llvm::(anonymous namespace)::D4_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L13D4_SubRegsSetE", "llvm::(anonymous namespace)::D4_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L15D4_SuperRegsSetE", "llvm::(anonymous namespace)::D4_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L11D5_OverlapsE", "llvm::(anonymous namespace)::D5_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L13D5_SubRegsSetE", "llvm::(anonymous namespace)::D5_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L15D5_SuperRegsSetE", "llvm::(anonymous namespace)::D5_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L11D6_OverlapsE", "llvm::(anonymous namespace)::D6_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L13D6_SubRegsSetE", "llvm::(anonymous namespace)::D6_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L15D6_SuperRegsSetE", "llvm::(anonymous namespace)::D6_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L11D7_OverlapsE", "llvm::(anonymous namespace)::D7_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L13D7_SubRegsSetE", "llvm::(anonymous namespace)::D7_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L15D7_SuperRegsSetE", "llvm::(anonymous namespace)::D7_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L11D8_OverlapsE", "llvm::(anonymous namespace)::D8_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L13D8_SubRegsSetE", "llvm::(anonymous namespace)::D8_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L15D8_SuperRegsSetE", "llvm::(anonymous namespace)::D8_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L11D9_OverlapsE", "llvm::(anonymous namespace)::D9_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L13D9_SubRegsSetE", "llvm::(anonymous namespace)::D9_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L15D9_SuperRegsSetE", "llvm::(anonymous namespace)::D9_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12D10_OverlapsE", "llvm::(anonymous namespace)::D10_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L14D10_SubRegsSetE", "llvm::(anonymous namespace)::D10_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16D10_SuperRegsSetE", "llvm::(anonymous namespace)::D10_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12D11_OverlapsE", "llvm::(anonymous namespace)::D11_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L14D11_SubRegsSetE", "llvm::(anonymous namespace)::D11_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16D11_SuperRegsSetE", "llvm::(anonymous namespace)::D11_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12D12_OverlapsE", "llvm::(anonymous namespace)::D12_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L14D12_SubRegsSetE", "llvm::(anonymous namespace)::D12_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16D12_SuperRegsSetE", "llvm::(anonymous namespace)::D12_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12D13_OverlapsE", "llvm::(anonymous namespace)::D13_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L14D13_SubRegsSetE", "llvm::(anonymous namespace)::D13_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16D13_SuperRegsSetE", "llvm::(anonymous namespace)::D13_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12D14_OverlapsE", "llvm::(anonymous namespace)::D14_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L14D14_SubRegsSetE", "llvm::(anonymous namespace)::D14_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16D14_SuperRegsSetE", "llvm::(anonymous namespace)::D14_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12D15_OverlapsE", "llvm::(anonymous namespace)::D15_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L14D15_SubRegsSetE", "llvm::(anonymous namespace)::D15_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16D15_SuperRegsSetE", "llvm::(anonymous namespace)::D15_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12D16_OverlapsE", "llvm::(anonymous namespace)::D16_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16D16_SuperRegsSetE", "llvm::(anonymous namespace)::D16_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12D17_OverlapsE", "llvm::(anonymous namespace)::D17_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16D17_SuperRegsSetE", "llvm::(anonymous namespace)::D17_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12D18_OverlapsE", "llvm::(anonymous namespace)::D18_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16D18_SuperRegsSetE", "llvm::(anonymous namespace)::D18_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12D19_OverlapsE", "llvm::(anonymous namespace)::D19_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16D19_SuperRegsSetE", "llvm::(anonymous namespace)::D19_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12D20_OverlapsE", "llvm::(anonymous namespace)::D20_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16D20_SuperRegsSetE", "llvm::(anonymous namespace)::D20_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12D21_OverlapsE", "llvm::(anonymous namespace)::D21_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16D21_SuperRegsSetE", "llvm::(anonymous namespace)::D21_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12D22_OverlapsE", "llvm::(anonymous namespace)::D22_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16D22_SuperRegsSetE", "llvm::(anonymous namespace)::D22_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12D23_OverlapsE", "llvm::(anonymous namespace)::D23_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16D23_SuperRegsSetE", "llvm::(anonymous namespace)::D23_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12D24_OverlapsE", "llvm::(anonymous namespace)::D24_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16D24_SuperRegsSetE", "llvm::(anonymous namespace)::D24_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12D25_OverlapsE", "llvm::(anonymous namespace)::D25_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16D25_SuperRegsSetE", "llvm::(anonymous namespace)::D25_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12D26_OverlapsE", "llvm::(anonymous namespace)::D26_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16D26_SuperRegsSetE", "llvm::(anonymous namespace)::D26_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12D27_OverlapsE", "llvm::(anonymous namespace)::D27_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16D27_SuperRegsSetE", "llvm::(anonymous namespace)::D27_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12D28_OverlapsE", "llvm::(anonymous namespace)::D28_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16D28_SuperRegsSetE", "llvm::(anonymous namespace)::D28_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12D29_OverlapsE", "llvm::(anonymous namespace)::D29_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16D29_SuperRegsSetE", "llvm::(anonymous namespace)::D29_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12D30_OverlapsE", "llvm::(anonymous namespace)::D30_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16D30_SuperRegsSetE", "llvm::(anonymous namespace)::D30_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12D31_OverlapsE", "llvm::(anonymous namespace)::D31_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16D31_SuperRegsSetE", "llvm::(anonymous namespace)::D31_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L14FPEXC_OverlapsE", "llvm::(anonymous namespace)::FPEXC_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L14FPSCR_OverlapsE", "llvm::(anonymous namespace)::FPSCR_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L14FPSID_OverlapsE", "llvm::(anonymous namespace)::FPSID_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16ITSTATE_OverlapsE", "llvm::(anonymous namespace)::ITSTATE_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L11LR_OverlapsE", "llvm::(anonymous namespace)::LR_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L11PC_OverlapsE", "llvm::(anonymous namespace)::PC_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L11Q0_OverlapsE", "llvm::(anonymous namespace)::Q0_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L13Q0_SubRegsSetE", "llvm::(anonymous namespace)::Q0_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L15Q0_SuperRegsSetE", "llvm::(anonymous namespace)::Q0_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L11Q1_OverlapsE", "llvm::(anonymous namespace)::Q1_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L13Q1_SubRegsSetE", "llvm::(anonymous namespace)::Q1_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L15Q1_SuperRegsSetE", "llvm::(anonymous namespace)::Q1_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L11Q2_OverlapsE", "llvm::(anonymous namespace)::Q2_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L13Q2_SubRegsSetE", "llvm::(anonymous namespace)::Q2_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L15Q2_SuperRegsSetE", "llvm::(anonymous namespace)::Q2_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L11Q3_OverlapsE", "llvm::(anonymous namespace)::Q3_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L13Q3_SubRegsSetE", "llvm::(anonymous namespace)::Q3_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L15Q3_SuperRegsSetE", "llvm::(anonymous namespace)::Q3_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L11Q4_OverlapsE", "llvm::(anonymous namespace)::Q4_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L13Q4_SubRegsSetE", "llvm::(anonymous namespace)::Q4_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L15Q4_SuperRegsSetE", "llvm::(anonymous namespace)::Q4_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L11Q5_OverlapsE", "llvm::(anonymous namespace)::Q5_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L13Q5_SubRegsSetE", "llvm::(anonymous namespace)::Q5_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L15Q5_SuperRegsSetE", "llvm::(anonymous namespace)::Q5_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L11Q6_OverlapsE", "llvm::(anonymous namespace)::Q6_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L13Q6_SubRegsSetE", "llvm::(anonymous namespace)::Q6_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L15Q6_SuperRegsSetE", "llvm::(anonymous namespace)::Q6_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L11Q7_OverlapsE", "llvm::(anonymous namespace)::Q7_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L13Q7_SubRegsSetE", "llvm::(anonymous namespace)::Q7_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L15Q7_SuperRegsSetE", "llvm::(anonymous namespace)::Q7_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L11Q8_OverlapsE", "llvm::(anonymous namespace)::Q8_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L13Q8_SubRegsSetE", "llvm::(anonymous namespace)::Q8_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L15Q8_SuperRegsSetE", "llvm::(anonymous namespace)::Q8_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L11Q9_OverlapsE", "llvm::(anonymous namespace)::Q9_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L13Q9_SubRegsSetE", "llvm::(anonymous namespace)::Q9_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L15Q9_SuperRegsSetE", "llvm::(anonymous namespace)::Q9_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12Q10_OverlapsE", "llvm::(anonymous namespace)::Q10_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L14Q10_SubRegsSetE", "llvm::(anonymous namespace)::Q10_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16Q10_SuperRegsSetE", "llvm::(anonymous namespace)::Q10_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12Q11_OverlapsE", "llvm::(anonymous namespace)::Q11_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L14Q11_SubRegsSetE", "llvm::(anonymous namespace)::Q11_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16Q11_SuperRegsSetE", "llvm::(anonymous namespace)::Q11_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12Q12_OverlapsE", "llvm::(anonymous namespace)::Q12_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L14Q12_SubRegsSetE", "llvm::(anonymous namespace)::Q12_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16Q12_SuperRegsSetE", "llvm::(anonymous namespace)::Q12_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12Q13_OverlapsE", "llvm::(anonymous namespace)::Q13_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L14Q13_SubRegsSetE", "llvm::(anonymous namespace)::Q13_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16Q13_SuperRegsSetE", "llvm::(anonymous namespace)::Q13_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12Q14_OverlapsE", "llvm::(anonymous namespace)::Q14_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L14Q14_SubRegsSetE", "llvm::(anonymous namespace)::Q14_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16Q14_SuperRegsSetE", "llvm::(anonymous namespace)::Q14_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12Q15_OverlapsE", "llvm::(anonymous namespace)::Q15_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L14Q15_SubRegsSetE", "llvm::(anonymous namespace)::Q15_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16Q15_SuperRegsSetE", "llvm::(anonymous namespace)::Q15_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12QQ0_OverlapsE", "llvm::(anonymous namespace)::QQ0_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L14QQ0_SubRegsSetE", "llvm::(anonymous namespace)::QQ0_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16QQ0_SuperRegsSetE", "llvm::(anonymous namespace)::QQ0_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12QQ1_OverlapsE", "llvm::(anonymous namespace)::QQ1_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L14QQ1_SubRegsSetE", "llvm::(anonymous namespace)::QQ1_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16QQ1_SuperRegsSetE", "llvm::(anonymous namespace)::QQ1_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12QQ2_OverlapsE", "llvm::(anonymous namespace)::QQ2_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L14QQ2_SubRegsSetE", "llvm::(anonymous namespace)::QQ2_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16QQ2_SuperRegsSetE", "llvm::(anonymous namespace)::QQ2_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12QQ3_OverlapsE", "llvm::(anonymous namespace)::QQ3_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L14QQ3_SubRegsSetE", "llvm::(anonymous namespace)::QQ3_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16QQ3_SuperRegsSetE", "llvm::(anonymous namespace)::QQ3_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12QQ4_OverlapsE", "llvm::(anonymous namespace)::QQ4_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L14QQ4_SubRegsSetE", "llvm::(anonymous namespace)::QQ4_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16QQ4_SuperRegsSetE", "llvm::(anonymous namespace)::QQ4_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12QQ5_OverlapsE", "llvm::(anonymous namespace)::QQ5_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L14QQ5_SubRegsSetE", "llvm::(anonymous namespace)::QQ5_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16QQ5_SuperRegsSetE", "llvm::(anonymous namespace)::QQ5_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12QQ6_OverlapsE", "llvm::(anonymous namespace)::QQ6_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L14QQ6_SubRegsSetE", "llvm::(anonymous namespace)::QQ6_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16QQ6_SuperRegsSetE", "llvm::(anonymous namespace)::QQ6_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12QQ7_OverlapsE", "llvm::(anonymous namespace)::QQ7_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L14QQ7_SubRegsSetE", "llvm::(anonymous namespace)::QQ7_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16QQ7_SuperRegsSetE", "llvm::(anonymous namespace)::QQ7_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L14QQQQ0_OverlapsE", "llvm::(anonymous namespace)::QQQQ0_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16QQQQ0_SubRegsSetE", "llvm::(anonymous namespace)::QQQQ0_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L14QQQQ1_OverlapsE", "llvm::(anonymous namespace)::QQQQ1_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16QQQQ1_SubRegsSetE", "llvm::(anonymous namespace)::QQQQ1_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L14QQQQ2_OverlapsE", "llvm::(anonymous namespace)::QQQQ2_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16QQQQ2_SubRegsSetE", "llvm::(anonymous namespace)::QQQQ2_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L14QQQQ3_OverlapsE", "llvm::(anonymous namespace)::QQQQ3_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16QQQQ3_SubRegsSetE", "llvm::(anonymous namespace)::QQQQ3_SubRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L11R0_OverlapsE", "llvm::(anonymous namespace)::R0_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L11R1_OverlapsE", "llvm::(anonymous namespace)::R1_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L11R2_OverlapsE", "llvm::(anonymous namespace)::R2_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L11R3_OverlapsE", "llvm::(anonymous namespace)::R3_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L11R4_OverlapsE", "llvm::(anonymous namespace)::R4_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L11R5_OverlapsE", "llvm::(anonymous namespace)::R5_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L11R6_OverlapsE", "llvm::(anonymous namespace)::R6_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L11R7_OverlapsE", "llvm::(anonymous namespace)::R7_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L11R8_OverlapsE", "llvm::(anonymous namespace)::R8_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L11R9_OverlapsE", "llvm::(anonymous namespace)::R9_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12R10_OverlapsE", "llvm::(anonymous namespace)::R10_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12R11_OverlapsE", "llvm::(anonymous namespace)::R11_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12R12_OverlapsE", "llvm::(anonymous namespace)::R12_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L11S0_OverlapsE", "llvm::(anonymous namespace)::S0_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L15S0_SuperRegsSetE", "llvm::(anonymous namespace)::S0_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L11S1_OverlapsE", "llvm::(anonymous namespace)::S1_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L15S1_SuperRegsSetE", "llvm::(anonymous namespace)::S1_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L11S2_OverlapsE", "llvm::(anonymous namespace)::S2_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L15S2_SuperRegsSetE", "llvm::(anonymous namespace)::S2_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L11S3_OverlapsE", "llvm::(anonymous namespace)::S3_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L15S3_SuperRegsSetE", "llvm::(anonymous namespace)::S3_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L11S4_OverlapsE", "llvm::(anonymous namespace)::S4_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L15S4_SuperRegsSetE", "llvm::(anonymous namespace)::S4_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L11S5_OverlapsE", "llvm::(anonymous namespace)::S5_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L15S5_SuperRegsSetE", "llvm::(anonymous namespace)::S5_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L11S6_OverlapsE", "llvm::(anonymous namespace)::S6_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L15S6_SuperRegsSetE", "llvm::(anonymous namespace)::S6_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L11S7_OverlapsE", "llvm::(anonymous namespace)::S7_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L15S7_SuperRegsSetE", "llvm::(anonymous namespace)::S7_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L11S8_OverlapsE", "llvm::(anonymous namespace)::S8_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L15S8_SuperRegsSetE", "llvm::(anonymous namespace)::S8_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L11S9_OverlapsE", "llvm::(anonymous namespace)::S9_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L15S9_SuperRegsSetE", "llvm::(anonymous namespace)::S9_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12S10_OverlapsE", "llvm::(anonymous namespace)::S10_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16S10_SuperRegsSetE", "llvm::(anonymous namespace)::S10_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12S11_OverlapsE", "llvm::(anonymous namespace)::S11_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16S11_SuperRegsSetE", "llvm::(anonymous namespace)::S11_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12S12_OverlapsE", "llvm::(anonymous namespace)::S12_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16S12_SuperRegsSetE", "llvm::(anonymous namespace)::S12_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12S13_OverlapsE", "llvm::(anonymous namespace)::S13_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16S13_SuperRegsSetE", "llvm::(anonymous namespace)::S13_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12S14_OverlapsE", "llvm::(anonymous namespace)::S14_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16S14_SuperRegsSetE", "llvm::(anonymous namespace)::S14_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12S15_OverlapsE", "llvm::(anonymous namespace)::S15_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16S15_SuperRegsSetE", "llvm::(anonymous namespace)::S15_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12S16_OverlapsE", "llvm::(anonymous namespace)::S16_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16S16_SuperRegsSetE", "llvm::(anonymous namespace)::S16_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12S17_OverlapsE", "llvm::(anonymous namespace)::S17_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16S17_SuperRegsSetE", "llvm::(anonymous namespace)::S17_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12S18_OverlapsE", "llvm::(anonymous namespace)::S18_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16S18_SuperRegsSetE", "llvm::(anonymous namespace)::S18_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12S19_OverlapsE", "llvm::(anonymous namespace)::S19_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16S19_SuperRegsSetE", "llvm::(anonymous namespace)::S19_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12S20_OverlapsE", "llvm::(anonymous namespace)::S20_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16S20_SuperRegsSetE", "llvm::(anonymous namespace)::S20_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12S21_OverlapsE", "llvm::(anonymous namespace)::S21_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16S21_SuperRegsSetE", "llvm::(anonymous namespace)::S21_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12S22_OverlapsE", "llvm::(anonymous namespace)::S22_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16S22_SuperRegsSetE", "llvm::(anonymous namespace)::S22_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12S23_OverlapsE", "llvm::(anonymous namespace)::S23_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16S23_SuperRegsSetE", "llvm::(anonymous namespace)::S23_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12S24_OverlapsE", "llvm::(anonymous namespace)::S24_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16S24_SuperRegsSetE", "llvm::(anonymous namespace)::S24_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12S25_OverlapsE", "llvm::(anonymous namespace)::S25_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16S25_SuperRegsSetE", "llvm::(anonymous namespace)::S25_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12S26_OverlapsE", "llvm::(anonymous namespace)::S26_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16S26_SuperRegsSetE", "llvm::(anonymous namespace)::S26_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12S27_OverlapsE", "llvm::(anonymous namespace)::S27_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16S27_SuperRegsSetE", "llvm::(anonymous namespace)::S27_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12S28_OverlapsE", "llvm::(anonymous namespace)::S28_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16S28_SuperRegsSetE", "llvm::(anonymous namespace)::S28_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12S29_OverlapsE", "llvm::(anonymous namespace)::S29_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16S29_SuperRegsSetE", "llvm::(anonymous namespace)::S29_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12S30_OverlapsE", "llvm::(anonymous namespace)::S30_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16S30_SuperRegsSetE", "llvm::(anonymous namespace)::S30_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L12S31_OverlapsE", "llvm::(anonymous namespace)::S31_Overlaps"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16S31_SuperRegsSetE", "llvm::(anonymous namespace)::S31_SuperRegsSet"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L11SP_OverlapsE", "llvm::(anonymous namespace)::SP_Overlaps"),
	mu_demangle_test("_ZL19PerfectShuffleTable", "PerfectShuffleTable"),
	mu_demangle_test("_ZL13OperandCycles", "OperandCycles"),
	mu_demangle_test("_ZL16ForwardingPathes", "ForwardingPathes"),
	mu_demangle_test("_ZN4llvm9AttributeL20MutuallyIncompatibleE", "llvm::Attribute::MutuallyIncompatible"),
	mu_demangle_test("_ZL14hexDigitsUpper", "hexDigitsUpper"),
	mu_demangle_test("_ZL14hexDigitsLower", "hexDigitsLower"),
	mu_demangle_test("_ZL10colorcodes", "colorcodes"),
	mu_demangle_test("_ZL7IntSigs", "IntSigs"),
	mu_demangle_test("_ZL8KillSigs", "KillSigs"),
	mu_demangle_test("_ZN12_GLOBAL__N_1L11GCCRegNamesE", "(anonymous namespace)::GCCRegNames"),
	mu_demangle_test("_ZL8TokNames", "TokNames"),
	mu_demangle_test("_ZN4llvmL16CallGraphLinkObjE", "llvm::CallGraphLinkObj"),
	mu_demangle_test("_ZN4llvmL16CallGraphLinkObjE", "llvm::CallGraphLinkObj"),
	mu_demangle_test("_ZN4llvmL16CallGraphLinkObjE", "llvm::CallGraphLinkObj"),
	mu_demangle_test("_ZN4llvmL16CallGraphLinkObjE", "llvm::CallGraphLinkObj"),
	mu_demangle_test("_ZN4llvmL16CallGraphLinkObjE", "llvm::CallGraphLinkObj"),
	mu_demangle_test("_ZN4llvmL16CallGraphLinkObjE", "llvm::CallGraphLinkObj"),
	mu_demangle_test("_ZL13x86_asm_table", "x86_asm_table"),
	mu_demangle_test("_ZN4llvm3X86L19FR32SuperRegClassesE", "llvm::X86::FR32SuperRegClasses"),
	mu_demangle_test("_ZN4llvm3X86L19FR64SuperRegClassesE", "llvm::X86::FR64SuperRegClasses"),
	mu_demangle_test("_ZN4llvm3X86L19GR16SuperRegClassesE", "llvm::X86::GR16SuperRegClasses"),
	mu_demangle_test("_ZN4llvm3X86L24GR16_ABCDSuperRegClassesE", "llvm::X86::GR16_ABCDSuperRegClasses"),
	mu_demangle_test("_ZN4llvm3X86L25GR16_NOREXSuperRegClassesE", "llvm::X86::GR16_NOREXSuperRegClasses"),
	mu_demangle_test("_ZN4llvm3X86L19GR32SuperRegClassesE", "llvm::X86::GR32SuperRegClasses"),
	mu_demangle_test("_ZN4llvm3X86L24GR32_ABCDSuperRegClassesE", "llvm::X86::GR32_ABCDSuperRegClasses"),
	mu_demangle_test("_ZN4llvm3X86L25GR32_NOREXSuperRegClassesE", "llvm::X86::GR32_NOREXSuperRegClasses"),
	mu_demangle_test("_ZN4llvm3X86L24GR32_NOSPSuperRegClassesE", "llvm::X86::GR32_NOSPSuperRegClasses"),
	mu_demangle_test("_ZN4llvm3X86L22GR32_TCSuperRegClassesE", "llvm::X86::GR32_TCSuperRegClasses"),
	mu_demangle_test("_ZN4llvm3X86L18GR8SuperRegClassesE", "llvm::X86::GR8SuperRegClasses"),
	mu_demangle_test("_ZN4llvm3X86L25GR8_ABCD_HSuperRegClassesE", "llvm::X86::GR8_ABCD_HSuperRegClasses"),
	mu_demangle_test("_ZN4llvm3X86L25GR8_ABCD_LSuperRegClassesE", "llvm::X86::GR8_ABCD_LSuperRegClasses"),
	mu_demangle_test("_ZN4llvm3X86L24GR8_NOREXSuperRegClassesE", "llvm::X86::GR8_NOREXSuperRegClasses"),
	mu_demangle_test("_ZN4llvm3X86L20VR128SuperRegClassesE", "llvm::X86::VR128SuperRegClasses"),
	mu_demangle_test("_ZN4llvm3X86L14FR32SubclassesE", "llvm::X86::FR32Subclasses"),
	mu_demangle_test("_ZN4llvm3X86L14FR64SubclassesE", "llvm::X86::FR64Subclasses"),
	mu_demangle_test("_ZN4llvm3X86L14GR16SubclassesE", "llvm::X86::GR16Subclasses"),
	mu_demangle_test("_ZN4llvm3X86L20GR16_NOREXSubclassesE", "llvm::X86::GR16_NOREXSubclasses"),
	mu_demangle_test("_ZN4llvm3X86L14GR32SubclassesE", "llvm::X86::GR32Subclasses"),
	mu_demangle_test("_ZN4llvm3X86L19GR32_ABCDSubclassesE", "llvm::X86::GR32_ABCDSubclasses"),
	mu_demangle_test("_ZN4llvm3X86L20GR32_NOREXSubclassesE", "llvm::X86::GR32_NOREXSubclasses"),
	mu_demangle_test("_ZN4llvm3X86L19GR32_NOSPSubclassesE", "llvm::X86::GR32_NOSPSubclasses"),
	mu_demangle_test("_ZN4llvm3X86L17GR32_TCSubclassesE", "llvm::X86::GR32_TCSubclasses"),
	mu_demangle_test("_ZN4llvm3X86L14GR64SubclassesE", "llvm::X86::GR64Subclasses"),
	mu_demangle_test("_ZN4llvm3X86L20GR64_NOREXSubclassesE", "llvm::X86::GR64_NOREXSubclasses"),
	mu_demangle_test("_ZN4llvm3X86L25GR64_NOREX_NOSPSubclassesE", "llvm::X86::GR64_NOREX_NOSPSubclasses"),
	mu_demangle_test("_ZN4llvm3X86L19GR64_NOSPSubclassesE", "llvm::X86::GR64_NOSPSubclasses"),
	mu_demangle_test("_ZN4llvm3X86L17GR64_TCSubclassesE", "llvm::X86::GR64_TCSubclasses"),
	mu_demangle_test("_ZN4llvm3X86L13GR8SubclassesE", "llvm::X86::GR8Subclasses"),
	mu_demangle_test("_ZN4llvm3X86L19GR8_NOREXSubclassesE", "llvm::X86::GR8_NOREXSubclasses"),
	mu_demangle_test("_ZN4llvm3X86L15RFP32SubclassesE", "llvm::X86::RFP32Subclasses"),
	mu_demangle_test("_ZN4llvm3X86L15RFP64SubclassesE", "llvm::X86::RFP64Subclasses"),
	mu_demangle_test("_ZN4llvm3X86L16FR64SuperclassesE", "llvm::X86::FR64Superclasses"),
	mu_demangle_test("_ZN4llvm3X86L21GR16_ABCDSuperclassesE", "llvm::X86::GR16_ABCDSuperclasses"),
	mu_demangle_test("_ZN4llvm3X86L22GR16_NOREXSuperclassesE", "llvm::X86::GR16_NOREXSuperclasses"),
	mu_demangle_test("_ZN4llvm3X86L21GR32_ABCDSuperclassesE", "llvm::X86::GR32_ABCDSuperclasses"),
	mu_demangle_test("_ZN4llvm3X86L19GR32_ADSuperclassesE", "llvm::X86::GR32_ADSuperclasses"),
	mu_demangle_test("_ZN4llvm3X86L22GR32_NOREXSuperclassesE", "llvm::X86::GR32_NOREXSuperclasses"),
	mu_demangle_test("_ZN4llvm3X86L21GR32_NOSPSuperclassesE", "llvm::X86::GR32_NOSPSuperclasses"),
	mu_demangle_test("_ZN4llvm3X86L19GR32_TCSuperclassesE", "llvm::X86::GR32_TCSuperclasses"),
	mu_demangle_test("_ZN4llvm3X86L21GR64_ABCDSuperclassesE", "llvm::X86::GR64_ABCDSuperclasses"),
	mu_demangle_test("_ZN4llvm3X86L22GR64_NOREXSuperclassesE", "llvm::X86::GR64_NOREXSuperclasses"),
	mu_demangle_test("_ZN4llvm3X86L27GR64_NOREX_NOSPSuperclassesE", "llvm::X86::GR64_NOREX_NOSPSuperclasses"),
	mu_demangle_test("_ZN4llvm3X86L21GR64_NOSPSuperclassesE", "llvm::X86::GR64_NOSPSuperclasses"),
	mu_demangle_test("_ZN4llvm3X86L19GR64_TCSuperclassesE", "llvm::X86::GR64_TCSuperclasses"),
	mu_demangle_test("_ZN4llvm3X86L22GR64_TCW64SuperclassesE", "llvm::X86::GR64_TCW64Superclasses"),
	mu_demangle_test("_ZN4llvm3X86L22GR8_ABCD_HSuperclassesE", "llvm::X86::GR8_ABCD_HSuperclasses"),
	mu_demangle_test("_ZN4llvm3X86L22GR8_ABCD_LSuperclassesE", "llvm::X86::GR8_ABCD_LSuperclasses"),
	mu_demangle_test("_ZN4llvm3X86L21GR8_NOREXSuperclassesE", "llvm::X86::GR8_NOREXSuperclasses"),
	mu_demangle_test("_ZN4llvm3X86L17RFP64SuperclassesE", "llvm::X86::RFP64Superclasses"),
	mu_demangle_test("_ZN4llvm3X86L17RFP80SuperclassesE", "llvm::X86::RFP80Superclasses"),
	mu_demangle_test("_ZN4llvm3X86L17VR128SuperclassesE", "llvm::X86::VR128Superclasses"),
	mu_demangle_test("_ZN4llvm3X86L17GR16SubRegClassesE", "llvm::X86::GR16SubRegClasses"),
	mu_demangle_test("_ZN4llvm3X86L22GR16_ABCDSubRegClassesE", "llvm::X86::GR16_ABCDSubRegClasses"),
	mu_demangle_test("_ZN4llvm3X86L23GR16_NOREXSubRegClassesE", "llvm::X86::GR16_NOREXSubRegClasses"),
	mu_demangle_test("_ZN4llvm3X86L17GR32SubRegClassesE", "llvm::X86::GR32SubRegClasses"),
	mu_demangle_test("_ZN4llvm3X86L22GR32_ABCDSubRegClassesE", "llvm::X86::GR32_ABCDSubRegClasses"),
	mu_demangle_test("_ZN4llvm3X86L20GR32_ADSubRegClassesE", "llvm::X86::GR32_ADSubRegClasses"),
	mu_demangle_test("_ZN4llvm3X86L23GR32_NOREXSubRegClassesE", "llvm::X86::GR32_NOREXSubRegClasses"),
	mu_demangle_test("_ZN4llvm3X86L22GR32_NOSPSubRegClassesE", "llvm::X86::GR32_NOSPSubRegClasses"),
	mu_demangle_test("_ZN4llvm3X86L20GR32_TCSubRegClassesE", "llvm::X86::GR32_TCSubRegClasses"),
	mu_demangle_test("_ZN4llvm3X86L17GR64SubRegClassesE", "llvm::X86::GR64SubRegClasses"),
	mu_demangle_test("_ZN4llvm3X86L22GR64_ABCDSubRegClassesE", "llvm::X86::GR64_ABCDSubRegClasses"),
	mu_demangle_test("_ZN4llvm3X86L23GR64_NOREXSubRegClassesE", "llvm::X86::GR64_NOREXSubRegClasses"),
	mu_demangle_test("_ZN4llvm3X86L28GR64_NOREX_NOSPSubRegClassesE", "llvm::X86::GR64_NOREX_NOSPSubRegClasses"),
	mu_demangle_test("_ZN4llvm3X86L22GR64_NOSPSubRegClassesE", "llvm::X86::GR64_NOSPSubRegClasses"),
	mu_demangle_test("_ZN4llvm3X86L20GR64_TCSubRegClassesE", "llvm::X86::GR64_TCSubRegClasses"),
	mu_demangle_test("_ZN4llvm3X86L18VR128SubRegClassesE", "llvm::X86::VR128SubRegClasses"),
	mu_demangle_test("_ZN4llvm3X86L18VR256SubRegClassesE", "llvm::X86::VR256SubRegClasses"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L15RegisterClassesE", "llvm::(anonymous namespace)::RegisterClasses"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16SubRegIndexTableE", "llvm::(anonymous namespace)::SubRegIndexTable"),
	mu_demangle_test("_ZN4llvm3ARML18DPRSuperRegClassesE", "llvm::ARM::DPRSuperRegClasses"),
	mu_demangle_test("_ZN4llvm3ARML20DPR_8SuperRegClassesE", "llvm::ARM::DPR_8SuperRegClasses"),
	mu_demangle_test("_ZN4llvm3ARML23DPR_VFP2SuperRegClassesE", "llvm::ARM::DPR_VFP2SuperRegClasses"),
	mu_demangle_test("_ZN4llvm3ARML18QPRSuperRegClassesE", "llvm::ARM::QPRSuperRegClasses"),
	mu_demangle_test("_ZN4llvm3ARML23QPR_VFP2SuperRegClassesE", "llvm::ARM::QPR_VFP2SuperRegClasses"),
	mu_demangle_test("_ZN4llvm3ARML18SPRSuperRegClassesE", "llvm::ARM::SPRSuperRegClasses"),
	mu_demangle_test("_ZN4llvm3ARML20SPR_8SuperRegClassesE", "llvm::ARM::SPR_8SuperRegClasses"),
	mu_demangle_test("_ZN4llvm3ARML13DPRSubclassesE", "llvm::ARM::DPRSubclasses"),
	mu_demangle_test("_ZN4llvm3ARML18DPR_VFP2SubclassesE", "llvm::ARM::DPR_VFP2Subclasses"),
	mu_demangle_test("_ZN4llvm3ARML13GPRSubclassesE", "llvm::ARM::GPRSubclasses"),
	mu_demangle_test("_ZN4llvm3ARML13QPRSubclassesE", "llvm::ARM::QPRSubclasses"),
	mu_demangle_test("_ZN4llvm3ARML18QPR_VFP2SubclassesE", "llvm::ARM::QPR_VFP2Subclasses"),
	mu_demangle_test("_ZN4llvm3ARML14QQPRSubclassesE", "llvm::ARM::QQPRSubclasses"),
	mu_demangle_test("_ZN4llvm3ARML13SPRSubclassesE", "llvm::ARM::SPRSubclasses"),
	mu_demangle_test("_ZN4llvm3ARML14rGPRSubclassesE", "llvm::ARM::rGPRSubclasses"),
	mu_demangle_test("_ZN4llvm3ARML17DPR_8SuperclassesE", "llvm::ARM::DPR_8Superclasses"),
	mu_demangle_test("_ZN4llvm3ARML20DPR_VFP2SuperclassesE", "llvm::ARM::DPR_VFP2Superclasses"),
	mu_demangle_test("_ZN4llvm3ARML17QPR_8SuperclassesE", "llvm::ARM::QPR_8Superclasses"),
	mu_demangle_test("_ZN4llvm3ARML20QPR_VFP2SuperclassesE", "llvm::ARM::QPR_VFP2Superclasses"),
	mu_demangle_test("_ZN4llvm3ARML21QQPR_VFP2SuperclassesE", "llvm::ARM::QQPR_VFP2Superclasses"),
	mu_demangle_test("_ZN4llvm3ARML17SPR_8SuperclassesE", "llvm::ARM::SPR_8Superclasses"),
	mu_demangle_test("_ZN4llvm3ARML16rGPRSuperclassesE", "llvm::ARM::rGPRSuperclasses"),
	mu_demangle_test("_ZN4llvm3ARML16tGPRSuperclassesE", "llvm::ARM::tGPRSuperclasses"),
	mu_demangle_test("_ZN4llvm3ARML17tcGPRSuperclassesE", "llvm::ARM::tcGPRSuperclasses"),
	mu_demangle_test("_ZN4llvm3ARML18DPR_8SubRegClassesE", "llvm::ARM::DPR_8SubRegClasses"),
	mu_demangle_test("_ZN4llvm3ARML21DPR_VFP2SubRegClassesE", "llvm::ARM::DPR_VFP2SubRegClasses"),
	mu_demangle_test("_ZN4llvm3ARML16QPRSubRegClassesE", "llvm::ARM::QPRSubRegClasses"),
	mu_demangle_test("_ZN4llvm3ARML18QPR_8SubRegClassesE", "llvm::ARM::QPR_8SubRegClasses"),
	mu_demangle_test("_ZN4llvm3ARML21QPR_VFP2SubRegClassesE", "llvm::ARM::QPR_VFP2SubRegClasses"),
	mu_demangle_test("_ZN4llvm3ARML17QQPRSubRegClassesE", "llvm::ARM::QQPRSubRegClasses"),
	mu_demangle_test("_ZN4llvm3ARML22QQPR_VFP2SubRegClassesE", "llvm::ARM::QQPR_VFP2SubRegClasses"),
	mu_demangle_test("_ZN4llvm3ARML19QQQQPRSubRegClassesE", "llvm::ARM::QQQQPRSubRegClasses"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L15RegisterClassesE", "llvm::(anonymous namespace)::RegisterClasses"),
	mu_demangle_test("_ZN4llvm12_GLOBAL__N_1L16SubRegIndexTableE", "llvm::(anonymous namespace)::SubRegIndexTable"),
	mu_demangle_test("_ZL13arm_asm_table", "arm_asm_table"),
	mu_demangle_test("_ZN4llvmL24RegisterCoalescerLinkObjE", "llvm::RegisterCoalescerLinkObj"),
	mu_demangle_test("_ZN4llvmL31SimpleRegisterCoalescingLinkObjE", "llvm::SimpleRegisterCoalescingLinkObj"),
	mu_demangle_test("_ZL8PSVNames", "PSVNames"),
	mu_demangle_test("_ZN4llvmL24RegisterCoalescerLinkObjE", "llvm::RegisterCoalescerLinkObj"),
	mu_demangle_test("_ZN4llvmL31SimpleRegisterCoalescingLinkObjE", "llvm::SimpleRegisterCoalescingLinkObj"),
	mu_demangle_test("_ZN4llvmL24RegisterCoalescerLinkObjE", "llvm::RegisterCoalescerLinkObj"),
	mu_demangle_test("_ZN4llvmL31SimpleRegisterCoalescingLinkObjE", "llvm::SimpleRegisterCoalescingLinkObj"),
	mu_demangle_test("_ZN4llvmL24RegisterCoalescerLinkObjE", "llvm::RegisterCoalescerLinkObj"),
	mu_demangle_test("_ZN4llvmL31SimpleRegisterCoalescingLinkObjE", "llvm::SimpleRegisterCoalescingLinkObj"),
	mu_demangle_test("_ZN4llvmL16CallGraphLinkObjE", "llvm::CallGraphLinkObj"),
	mu_demangle_test("_ZN4llvmL16CallGraphLinkObjE", "llvm::CallGraphLinkObj"),
	mu_demangle_test("_ZN4llvmL16CallGraphLinkObjE", "llvm::CallGraphLinkObj"),
	mu_demangle_test("_ZL22SectionTypeDescriptors", "SectionTypeDescriptors"),
	mu_demangle_test("_ZL22SectionAttrDescriptors", "SectionAttrDescriptors"),
	mu_demangle_test("_ZL9Lang_cuda", "Lang_cuda"),
	mu_demangle_test("_ZL11Lang_opencl", "Lang_opencl"),
	mu_demangle_test("_ZL13Lang_gnucxx0x", "Lang_gnucxx0x"),
	mu_demangle_test("_ZL10Lang_cxx0x", "Lang_cxx0x"),
	mu_demangle_test("_ZL13Lang_gnucxx98", "Lang_gnucxx98"),
	mu_demangle_test("_ZL10Lang_cxx98", "Lang_cxx98"),
	mu_demangle_test("_ZL10Lang_gnu9x", "Lang_gnu9x"),
	mu_demangle_test("_ZL10Lang_gnu99", "Lang_gnu99"),
	mu_demangle_test("_ZL17Lang_iso9899_199x", "Lang_iso9899_199x"),
	mu_demangle_test("_ZL8Lang_c9x", "Lang_c9x"),
	mu_demangle_test("_ZL8Lang_c99", "Lang_c99"),
	mu_demangle_test("_ZL10Lang_gnu89", "Lang_gnu89"),
	mu_demangle_test("_ZL8Lang_c94", "Lang_c94"),
	mu_demangle_test("_ZL8Lang_c90", "Lang_c90"),
	mu_demangle_test("_ZL8Lang_c89", "Lang_c89"),
	mu_demangle_test("_ZL14CC1AsInfoTable", "CC1AsInfoTable"),
	mu_demangle_test("_ZL12CC1InfoTable", "CC1InfoTable"),
	mu_demangle_test("_ZL9InfoTable", "InfoTable"),
	mu_demangle_test("_ZL9TypeInfos", "TypeInfos"),
	mu_demangle_test("_ZL16EagerlyAssumeTag", "EagerlyAssumeTag"),
	mu_demangle_test("_ZL4Msgs", "Msgs"),
	mu_demangle_test("_ZL11BuiltinInfo", "BuiltinInfo"),
	mu_demangle_test("_ZL14StaticDiagInfo", "StaticDiagInfo"),
	mu_demangle_test("_ZL11OptionTable", "OptionTable"),
	mu_demangle_test("_ZN12_GLOBAL__N_1L11BuiltinInfoE", "(anonymous namespace)::BuiltinInfo"),
	mu_demangle_test("_ZN12_GLOBAL__N_1L13GCCRegAliasesE", "(anonymous namespace)::GCCRegAliases"),
	mu_demangle_test("_ZL21NumAggregatesPromoted", "NumAggregatesPromoted"),
	mu_demangle_test("_ZL20NumArgumentsPromoted", "NumArgumentsPromoted"),
	mu_demangle_test("_ZL16NumArgumentsDead", "NumArgumentsDead"),
	mu_demangle_test("_ZL20NumByValArgsPromoted", "NumByValArgsPromoted"),
	mu_demangle_test("_ZL9NumMerged", "NumMerged"),
	mu_demangle_test("_ZL29NumArgumentsReplacedWithUndef", "NumArgumentsReplacedWithUndef"),
	mu_demangle_test("_ZL22NumArgumentsEliminated", "NumArgumentsEliminated"),
	mu_demangle_test("_ZL20NumRetValsEliminated", "NumRetValsEliminated"),
	mu_demangle_test("_ZL9NumKilled", "NumKilled"),
	mu_demangle_test("_ZL10NumNoAlias", "NumNoAlias"),
	mu_demangle_test("_ZL12NumNoCapture", "NumNoCapture"),
	mu_demangle_test("_ZL11NumReadNone", "NumReadNone"),
	mu_demangle_test("_ZL11NumReadOnly", "NumReadOnly"),
	mu_demangle_test("_ZL10NumAliases", "NumAliases"),
	mu_demangle_test("_ZL12NumVariables", "NumVariables"),
	mu_demangle_test("_ZL12NumFunctions", "NumFunctions"),
	mu_demangle_test("_ZL17NumAliasesRemoved", "NumAliasesRemoved"),
	mu_demangle_test("_ZL18NumAliasesResolved", "NumAliasesResolved"),
	mu_demangle_test("_ZL15NumShrunkToBool", "NumShrunkToBool"),
	mu_demangle_test("_ZL10NumHeapSRA", "NumHeapSRA"),
	mu_demangle_test("_ZL11NumGlobUses", "NumGlobUses"),
	mu_demangle_test("_ZL13NumSubstitute", "NumSubstitute"),
	mu_demangle_test("_ZL6NumSRA", "NumSRA"),
	mu_demangle_test("_ZL9NumMarked", "NumMarked"),
	mu_demangle_test("_ZL12NumLocalized", "NumLocalized"),
	mu_demangle_test("_ZL10NumUnnamed", "NumUnnamed"),
	mu_demangle_test("_ZL10NumDeleted", "NumDeleted"),
	mu_demangle_test("_ZL17NumCtorsEvaluated", "NumCtorsEvaluated"),
	mu_demangle_test("_ZL14NumNestRemoved", "NumNestRemoved"),
	mu_demangle_test("_ZL14NumFastCallFns", "NumFastCallFns"),
	mu_demangle_test("_ZL12NumFnDeleted", "NumFnDeleted"),
	mu_demangle_test("_ZL10NumDeleted", "NumDeleted"),
	mu_demangle_test("_ZL10NumInlined", "NumInlined"),
	mu_demangle_test("_ZL16NumMergedAllocas", "NumMergedAllocas"),
	mu_demangle_test("_ZL15NumCallsDeleted", "NumCallsDeleted"),
	mu_demangle_test("_ZL10NumUnreach", "NumUnreach"),
	mu_demangle_test("_ZL10NumRemoved", "NumRemoved"),
	mu_demangle_test("_ZL17NumDeadPrototypes", "NumDeadPrototypes"),
	mu_demangle_test("_ZL10MatchTable", "MatchTable"),
	mu_demangle_test("_ZL10NumEmitted", "NumEmitted"),
	mu_demangle_test("_ZL7NumFXCH", "NumFXCH"),
	mu_demangle_test("_ZL8PopTable", "PopTable"),
	mu_demangle_test("_ZL11OpcodeTable", "OpcodeTable"),
	mu_demangle_test("_ZL15ForwardST0Table", "ForwardST0Table"),
	mu_demangle_test("_ZL15ReverseST0Table", "ReverseST0Table"),
	mu_demangle_test("_ZL15ForwardSTiTable", "ForwardSTiTable"),
	mu_demangle_test("_ZL15ReverseSTiTable", "ReverseSTiTable"),
	mu_demangle_test("_ZL5NumFP", "NumFP"),
	mu_demangle_test("_ZL12NumLoadMoved", "NumLoadMoved"),
	mu_demangle_test("_ZL12NumTailCalls", "NumTailCalls"),
	mu_demangle_test("_ZN4llvmL9Barriers1E", "llvm::Barriers1"),
	mu_demangle_test("_ZN4llvmL9Barriers2E", "llvm::Barriers2"),
	mu_demangle_test("_ZN4llvmL9Barriers3E", "llvm::Barriers3"),
	mu_demangle_test("_ZN4llvmL9Barriers4E", "llvm::Barriers4"),
	mu_demangle_test("_ZN4llvmL9Barriers5E", "llvm::Barriers5"),
	mu_demangle_test("_ZN4llvmL9Barriers6E", "llvm::Barriers6"),
	mu_demangle_test("_ZN4llvmL9Barriers7E", "llvm::Barriers7"),
	mu_demangle_test("_ZN4llvmL9Barriers8E", "llvm::Barriers8"),
	mu_demangle_test("_ZN4llvmL12OperandInfo2E", "llvm::OperandInfo2"),
	mu_demangle_test("_ZN4llvmL12OperandInfo3E", "llvm::OperandInfo3"),
	mu_demangle_test("_ZN4llvmL12OperandInfo4E", "llvm::OperandInfo4"),
	mu_demangle_test("_ZN4llvmL12OperandInfo5E", "llvm::OperandInfo5"),
	mu_demangle_test("_ZN4llvmL12OperandInfo6E", "llvm::OperandInfo6"),
	mu_demangle_test("_ZN4llvmL12OperandInfo7E", "llvm::OperandInfo7"),
	mu_demangle_test("_ZN4llvmL12OperandInfo8E", "llvm::OperandInfo8"),
	mu_demangle_test("_ZN4llvmL12OperandInfo9E", "llvm::OperandInfo9"),
	mu_demangle_test("_ZN4llvmL13OperandInfo10E", "llvm::OperandInfo10"),
	mu_demangle_test("_ZN4llvmL13OperandInfo11E", "llvm::OperandInfo11"),
	mu_demangle_test("_ZN4llvmL13OperandInfo12E", "llvm::OperandInfo12"),
	mu_demangle_test("_ZN4llvmL13OperandInfo13E", "llvm::OperandInfo13"),
	mu_demangle_test("_ZN4llvmL13OperandInfo14E", "llvm::OperandInfo14"),
	mu_demangle_test("_ZN4llvmL13OperandInfo15E", "llvm::OperandInfo15"),
	mu_demangle_test("_ZN4llvmL13OperandInfo16E", "llvm::OperandInfo16"),
	mu_demangle_test("_ZN4llvmL13OperandInfo17E", "llvm::OperandInfo17"),
	mu_demangle_test("_ZN4llvmL13OperandInfo18E", "llvm::OperandInfo18"),
	mu_demangle_test("_ZN4llvmL13OperandInfo19E", "llvm::OperandInfo19"),
	mu_demangle_test("_ZN4llvmL13OperandInfo20E", "llvm::OperandInfo20"),
	mu_demangle_test("_ZN4llvmL13OperandInfo21E", "llvm::OperandInfo21"),
	mu_demangle_test("_ZN4llvmL13OperandInfo22E", "llvm::OperandInfo22"),
	mu_demangle_test("_ZN4llvmL13OperandInfo23E", "llvm::OperandInfo23"),
	mu_demangle_test("_ZN4llvmL13OperandInfo24E", "llvm::OperandInfo24"),
	mu_demangle_test("_ZN4llvmL13OperandInfo25E", "llvm::OperandInfo25"),
	mu_demangle_test("_ZN4llvmL13OperandInfo26E", "llvm::OperandInfo26"),
	mu_demangle_test("_ZN4llvmL13OperandInfo27E", "llvm::OperandInfo27"),
	mu_demangle_test("_ZN4llvmL13OperandInfo28E", "llvm::OperandInfo28"),
	mu_demangle_test("_ZN4llvmL13OperandInfo29E", "llvm::OperandInfo29"),
	mu_demangle_test("_ZN4llvmL13OperandInfo30E", "llvm::OperandInfo30"),
	mu_demangle_test("_ZN4llvmL13OperandInfo31E", "llvm::OperandInfo31"),
	mu_demangle_test("_ZN4llvmL13OperandInfo32E", "llvm::OperandInfo32"),
	mu_demangle_test("_ZN4llvmL13OperandInfo33E", "llvm::OperandInfo33"),
	mu_demangle_test("_ZN4llvmL13OperandInfo34E", "llvm::OperandInfo34"),
	mu_demangle_test("_ZN4llvmL13OperandInfo35E", "llvm::OperandInfo35"),
	mu_demangle_test("_ZN4llvmL13OperandInfo36E", "llvm::OperandInfo36"),
	mu_demangle_test("_ZN4llvmL13OperandInfo37E", "llvm::OperandInfo37"),
	mu_demangle_test("_ZN4llvmL13OperandInfo38E", "llvm::OperandInfo38"),
	mu_demangle_test("_ZN4llvmL13OperandInfo39E", "llvm::OperandInfo39"),
	mu_demangle_test("_ZN4llvmL13OperandInfo40E", "llvm::OperandInfo40"),
	mu_demangle_test("_ZN4llvmL13OperandInfo41E", "llvm::OperandInfo41"),
	mu_demangle_test("_ZN4llvmL13OperandInfo42E", "llvm::OperandInfo42"),
	mu_demangle_test("_ZN4llvmL13OperandInfo43E", "llvm::OperandInfo43"),
	mu_demangle_test("_ZN4llvmL13OperandInfo44E", "llvm::OperandInfo44"),
	mu_demangle_test("_ZN4llvmL13OperandInfo45E", "llvm::OperandInfo45"),
	mu_demangle_test("_ZN4llvmL13OperandInfo46E", "llvm::OperandInfo46"),
	mu_demangle_test("_ZN4llvmL13OperandInfo47E", "llvm::OperandInfo47"),
	mu_demangle_test("_ZN4llvmL13OperandInfo48E", "llvm::OperandInfo48"),
	mu_demangle_test("_ZN4llvmL13OperandInfo49E", "llvm::OperandInfo49"),
	mu_demangle_test("_ZN4llvmL13OperandInfo50E", "llvm::OperandInfo50"),
	mu_demangle_test("_ZN4llvmL13OperandInfo51E", "llvm::OperandInfo51"),
	mu_demangle_test("_ZN4llvmL13OperandInfo52E", "llvm::OperandInfo52"),
	mu_demangle_test("_ZN4llvmL13OperandInfo53E", "llvm::OperandInfo53"),
	mu_demangle_test("_ZN4llvmL13OperandInfo54E", "llvm::OperandInfo54"),
	mu_demangle_test("_ZN4llvmL13OperandInfo55E", "llvm::OperandInfo55"),
	mu_demangle_test("_ZN4llvmL13OperandInfo56E", "llvm::OperandInfo56"),
	mu_demangle_test("_ZN4llvmL13OperandInfo57E", "llvm::OperandInfo57"),
	mu_demangle_test("_ZN4llvmL13OperandInfo58E", "llvm::OperandInfo58"),
	mu_demangle_test("_ZN4llvmL13OperandInfo59E", "llvm::OperandInfo59"),
	mu_demangle_test("_ZN4llvmL13OperandInfo60E", "llvm::OperandInfo60"),
	mu_demangle_test("_ZN4llvmL13OperandInfo61E", "llvm::OperandInfo61"),
	mu_demangle_test("_ZN4llvmL13OperandInfo62E", "llvm::OperandInfo62"),
	mu_demangle_test("_ZN4llvmL13OperandInfo63E", "llvm::OperandInfo63"),
	mu_demangle_test("_ZN4llvmL13OperandInfo64E", "llvm::OperandInfo64"),
	mu_demangle_test("_ZN4llvmL13OperandInfo65E", "llvm::OperandInfo65"),
	mu_demangle_test("_ZN4llvmL13OperandInfo66E", "llvm::OperandInfo66"),
	mu_demangle_test("_ZN4llvmL13OperandInfo67E", "llvm::OperandInfo67"),
	mu_demangle_test("_ZN4llvmL13OperandInfo68E", "llvm::OperandInfo68"),
	mu_demangle_test("_ZN4llvmL13OperandInfo69E", "llvm::OperandInfo69"),
	mu_demangle_test("_ZN4llvmL13OperandInfo70E", "llvm::OperandInfo70"),
	mu_demangle_test("_ZN4llvmL13OperandInfo71E", "llvm::OperandInfo71"),
	mu_demangle_test("_ZN4llvmL13OperandInfo72E", "llvm::OperandInfo72"),
	mu_demangle_test("_ZN4llvmL13OperandInfo73E", "llvm::OperandInfo73"),
	mu_demangle_test("_ZN4llvmL13OperandInfo74E", "llvm::OperandInfo74"),
	mu_demangle_test("_ZN4llvmL13OperandInfo75E", "llvm::OperandInfo75"),
	mu_demangle_test("_ZN4llvmL13OperandInfo76E", "llvm::OperandInfo76"),
	mu_demangle_test("_ZN4llvmL13OperandInfo77E", "llvm::OperandInfo77"),
	mu_demangle_test("_ZN4llvmL13OperandInfo78E", "llvm::OperandInfo78"),
	mu_demangle_test("_ZN4llvmL13OperandInfo79E", "llvm::OperandInfo79"),
	mu_demangle_test("_ZN4llvmL13OperandInfo80E", "llvm::OperandInfo80"),
	mu_demangle_test("_ZN4llvmL13OperandInfo81E", "llvm::OperandInfo81"),
	mu_demangle_test("_ZN4llvmL13OperandInfo82E", "llvm::OperandInfo82"),
	mu_demangle_test("_ZN4llvmL13OperandInfo83E", "llvm::OperandInfo83"),
	mu_demangle_test("_ZN4llvmL13OperandInfo84E", "llvm::OperandInfo84"),
	mu_demangle_test("_ZN4llvmL13OperandInfo85E", "llvm::OperandInfo85"),
	mu_demangle_test("_ZN4llvmL13OperandInfo86E", "llvm::OperandInfo86"),
	mu_demangle_test("_ZN4llvmL13OperandInfo87E", "llvm::OperandInfo87"),
	mu_demangle_test("_ZN4llvmL13OperandInfo88E", "llvm::OperandInfo88"),
	mu_demangle_test("_ZN4llvmL13OperandInfo89E", "llvm::OperandInfo89"),
	mu_demangle_test("_ZN4llvmL13OperandInfo90E", "llvm::OperandInfo90"),
	mu_demangle_test("_ZN4llvmL13OperandInfo91E", "llvm::OperandInfo91"),
	mu_demangle_test("_ZN4llvmL13OperandInfo92E", "llvm::OperandInfo92"),
	mu_demangle_test("_ZN4llvmL13OperandInfo93E", "llvm::OperandInfo93"),
	mu_demangle_test("_ZN4llvmL13OperandInfo94E", "llvm::OperandInfo94"),
	mu_demangle_test("_ZN4llvmL13OperandInfo95E", "llvm::OperandInfo95"),
	mu_demangle_test("_ZN4llvmL13OperandInfo96E", "llvm::OperandInfo96"),
	mu_demangle_test("_ZN4llvmL13OperandInfo97E", "llvm::OperandInfo97"),
	mu_demangle_test("_ZN4llvmL13OperandInfo98E", "llvm::OperandInfo98"),
	mu_demangle_test("_ZN4llvmL13OperandInfo99E", "llvm::OperandInfo99"),
	mu_demangle_test("_ZN4llvmL14OperandInfo100E", "llvm::OperandInfo100"),
	mu_demangle_test("_ZN4llvmL14OperandInfo101E", "llvm::OperandInfo101"),
	mu_demangle_test("_ZN4llvmL14OperandInfo102E", "llvm::OperandInfo102"),
	mu_demangle_test("_ZN4llvmL14OperandInfo103E", "llvm::OperandInfo103"),
	mu_demangle_test("_ZN4llvmL14OperandInfo104E", "llvm::OperandInfo104"),
	mu_demangle_test("_ZN4llvmL14OperandInfo105E", "llvm::OperandInfo105"),
	mu_demangle_test("_ZN4llvmL14OperandInfo106E", "llvm::OperandInfo106"),
	mu_demangle_test("_ZN4llvmL14OperandInfo107E", "llvm::OperandInfo107"),
	mu_demangle_test("_ZN4llvmL14OperandInfo108E", "llvm::OperandInfo108"),
	mu_demangle_test("_ZN4llvmL14OperandInfo109E", "llvm::OperandInfo109"),
	mu_demangle_test("_ZN4llvmL14OperandInfo110E", "llvm::OperandInfo110"),
	mu_demangle_test("_ZN4llvmL14OperandInfo111E", "llvm::OperandInfo111"),
	mu_demangle_test("_ZN4llvmL14OperandInfo112E", "llvm::OperandInfo112"),
	mu_demangle_test("_ZN4llvmL14OperandInfo113E", "llvm::OperandInfo113"),
	mu_demangle_test("_ZN4llvmL14OperandInfo114E", "llvm::OperandInfo114"),
	mu_demangle_test("_ZN4llvmL14OperandInfo115E", "llvm::OperandInfo115"),
	mu_demangle_test("_ZN4llvmL14OperandInfo116E", "llvm::OperandInfo116"),
	mu_demangle_test("_ZN4llvmL14OperandInfo117E", "llvm::OperandInfo117"),
	mu_demangle_test("_ZN4llvmL14OperandInfo118E", "llvm::OperandInfo118"),
	mu_demangle_test("_ZN4llvmL14OperandInfo119E", "llvm::OperandInfo119"),
	mu_demangle_test("_ZN4llvmL14OperandInfo120E", "llvm::OperandInfo120"),
	mu_demangle_test("_ZN4llvmL14OperandInfo121E", "llvm::OperandInfo121"),
	mu_demangle_test("_ZN4llvmL14OperandInfo122E", "llvm::OperandInfo122"),
	mu_demangle_test("_ZN4llvmL14OperandInfo123E", "llvm::OperandInfo123"),
	mu_demangle_test("_ZN4llvmL14OperandInfo124E", "llvm::OperandInfo124"),
	mu_demangle_test("_ZN4llvmL14OperandInfo125E", "llvm::OperandInfo125"),
	mu_demangle_test("_ZN4llvmL14OperandInfo126E", "llvm::OperandInfo126"),
	mu_demangle_test("_ZN4llvmL14OperandInfo127E", "llvm::OperandInfo127"),
	mu_demangle_test("_ZN4llvmL14OperandInfo128E", "llvm::OperandInfo128"),
	mu_demangle_test("_ZN4llvmL14OperandInfo129E", "llvm::OperandInfo129"),
	mu_demangle_test("_ZN4llvmL14OperandInfo130E", "llvm::OperandInfo130"),
	mu_demangle_test("_ZN4llvmL14OperandInfo131E", "llvm::OperandInfo131"),
	mu_demangle_test("_ZN4llvmL14OperandInfo132E", "llvm::OperandInfo132"),
	mu_demangle_test("_ZN4llvmL14OperandInfo133E", "llvm::OperandInfo133"),
	mu_demangle_test("_ZN4llvmL14OperandInfo134E", "llvm::OperandInfo134"),
	mu_demangle_test("_ZN4llvmL14OperandInfo135E", "llvm::OperandInfo135"),
	mu_demangle_test("_ZN4llvmL14OperandInfo136E", "llvm::OperandInfo136"),
	mu_demangle_test("_ZN4llvmL14OperandInfo137E", "llvm::OperandInfo137"),
	mu_demangle_test("_ZN4llvmL14OperandInfo138E", "llvm::OperandInfo138"),
	mu_demangle_test("_ZN4llvmL14OperandInfo139E", "llvm::OperandInfo139"),
	mu_demangle_test("_ZN4llvmL14OperandInfo140E", "llvm::OperandInfo140"),
	mu_demangle_test("_ZN4llvmL14OperandInfo141E", "llvm::OperandInfo141"),
	mu_demangle_test("_ZN4llvmL14OperandInfo142E", "llvm::OperandInfo142"),
	mu_demangle_test("_ZN4llvmL14OperandInfo143E", "llvm::OperandInfo143"),
	mu_demangle_test("_ZN4llvmL14OperandInfo144E", "llvm::OperandInfo144"),
	mu_demangle_test("_ZN4llvmL14OperandInfo145E", "llvm::OperandInfo145"),
	mu_demangle_test("_ZN4llvmL14OperandInfo146E", "llvm::OperandInfo146"),
	mu_demangle_test("_ZN4llvmL14OperandInfo147E", "llvm::OperandInfo147"),
	mu_demangle_test("_ZN4llvmL14OperandInfo148E", "llvm::OperandInfo148"),
	mu_demangle_test("_ZN4llvmL14OperandInfo149E", "llvm::OperandInfo149"),
	mu_demangle_test("_ZN4llvmL14OperandInfo150E", "llvm::OperandInfo150"),
	mu_demangle_test("_ZN4llvmL14OperandInfo151E", "llvm::OperandInfo151"),
	mu_demangle_test("_ZN4llvmL14OperandInfo152E", "llvm::OperandInfo152"),
	mu_demangle_test("_ZN4llvmL14OperandInfo153E", "llvm::OperandInfo153"),
	mu_demangle_test("_ZN4llvmL14OperandInfo154E", "llvm::OperandInfo154"),
	mu_demangle_test("_ZN4llvmL14OperandInfo155E", "llvm::OperandInfo155"),
	mu_demangle_test("_ZN4llvmL14OperandInfo156E", "llvm::OperandInfo156"),
	mu_demangle_test("_ZN4llvmL14OperandInfo157E", "llvm::OperandInfo157"),
	mu_demangle_test("_ZN4llvmL14OperandInfo158E", "llvm::OperandInfo158"),
	mu_demangle_test("_ZN4llvmL14OperandInfo159E", "llvm::OperandInfo159"),
	mu_demangle_test("_ZN4llvmL14OperandInfo160E", "llvm::OperandInfo160"),
	mu_demangle_test("_ZN4llvmL14OperandInfo161E", "llvm::OperandInfo161"),
	mu_demangle_test("_ZN4llvmL14OperandInfo162E", "llvm::OperandInfo162"),
	mu_demangle_test("_ZN4llvmL14OperandInfo163E", "llvm::OperandInfo163"),
	mu_demangle_test("_ZN4llvmL14OperandInfo164E", "llvm::OperandInfo164"),
	mu_demangle_test("_ZN4llvmL14OperandInfo165E", "llvm::OperandInfo165"),
	mu_demangle_test("_ZN4llvmL14OperandInfo166E", "llvm::OperandInfo166"),
	mu_demangle_test("_ZN4llvmL14OperandInfo167E", "llvm::OperandInfo167"),
	mu_demangle_test("_ZN4llvmL14OperandInfo168E", "llvm::OperandInfo168"),
	mu_demangle_test("_ZN4llvmL14OperandInfo169E", "llvm::OperandInfo169"),
	mu_demangle_test("_ZN4llvmL14OperandInfo170E", "llvm::OperandInfo170"),
	mu_demangle_test("_ZN4llvmL14OperandInfo171E", "llvm::OperandInfo171"),
	mu_demangle_test("_ZN4llvmL14OperandInfo172E", "llvm::OperandInfo172"),
	mu_demangle_test("_ZN4llvmL14OperandInfo173E", "llvm::OperandInfo173"),
	mu_demangle_test("_ZN4llvmL14OperandInfo174E", "llvm::OperandInfo174"),
	mu_demangle_test("_ZN4llvmL14OperandInfo175E", "llvm::OperandInfo175"),
	mu_demangle_test("_ZN4llvmL14OperandInfo176E", "llvm::OperandInfo176"),
	mu_demangle_test("_ZN4llvmL14OperandInfo177E", "llvm::OperandInfo177"),
	mu_demangle_test("_ZN4llvmL14OperandInfo178E", "llvm::OperandInfo178"),
	mu_demangle_test("_ZN4llvmL14OperandInfo179E", "llvm::OperandInfo179"),
	mu_demangle_test("_ZN4llvmL14OperandInfo180E", "llvm::OperandInfo180"),
	mu_demangle_test("_ZN4llvmL14OperandInfo181E", "llvm::OperandInfo181"),
	mu_demangle_test("_ZN4llvmL14OperandInfo182E", "llvm::OperandInfo182"),
	mu_demangle_test("_ZN4llvmL14OperandInfo183E", "llvm::OperandInfo183"),
	mu_demangle_test("_ZN4llvmL14OperandInfo184E", "llvm::OperandInfo184"),
	mu_demangle_test("_ZN4llvmL14OperandInfo185E", "llvm::OperandInfo185"),
	mu_demangle_test("_ZN4llvmL14OperandInfo186E", "llvm::OperandInfo186"),
	mu_demangle_test("_ZN4llvmL14OperandInfo187E", "llvm::OperandInfo187"),
	mu_demangle_test("_ZN4llvmL14OperandInfo188E", "llvm::OperandInfo188"),
	mu_demangle_test("_ZN4llvmL14OperandInfo189E", "llvm::OperandInfo189"),
	mu_demangle_test("_ZN4llvmL14OperandInfo190E", "llvm::OperandInfo190"),
	mu_demangle_test("_ZN4llvmL14OperandInfo191E", "llvm::OperandInfo191"),
	mu_demangle_test("_ZN4llvmL14OperandInfo192E", "llvm::OperandInfo192"),
	mu_demangle_test("_ZN4llvmL14OperandInfo193E", "llvm::OperandInfo193"),
	mu_demangle_test("_ZN4llvmL14OperandInfo194E", "llvm::OperandInfo194"),
	mu_demangle_test("_ZN4llvmL14OperandInfo195E", "llvm::OperandInfo195"),
	mu_demangle_test("_ZN4llvmL14OperandInfo196E", "llvm::OperandInfo196"),
	mu_demangle_test("_ZN4llvmL14OperandInfo197E", "llvm::OperandInfo197"),
	mu_demangle_test("_ZN4llvmL14OperandInfo198E", "llvm::OperandInfo198"),
	mu_demangle_test("_ZN4llvmL14OperandInfo199E", "llvm::OperandInfo199"),
	mu_demangle_test("_ZN4llvmL14OperandInfo200E", "llvm::OperandInfo200"),
	mu_demangle_test("_ZN4llvmL14OperandInfo201E", "llvm::OperandInfo201"),
	mu_demangle_test("_ZN4llvmL14OperandInfo202E", "llvm::OperandInfo202"),
	mu_demangle_test("_ZN4llvmL14OperandInfo203E", "llvm::OperandInfo203"),
	mu_demangle_test("_ZN4llvmL14OperandInfo204E", "llvm::OperandInfo204"),
	mu_demangle_test("_ZN4llvmL14OperandInfo205E", "llvm::OperandInfo205"),
	mu_demangle_test("_ZN4llvmL14OperandInfo206E", "llvm::OperandInfo206"),
	mu_demangle_test("_ZN4llvmL14OperandInfo207E", "llvm::OperandInfo207"),
	mu_demangle_test("_ZN4llvmL14OperandInfo208E", "llvm::OperandInfo208"),
	mu_demangle_test("_ZN4llvmL14OperandInfo209E", "llvm::OperandInfo209"),
	mu_demangle_test("_ZN4llvmL14OperandInfo210E", "llvm::OperandInfo210"),
	mu_demangle_test("_ZN4llvmL14OperandInfo211E", "llvm::OperandInfo211"),
	mu_demangle_test("_ZN4llvmL14OperandInfo212E", "llvm::OperandInfo212"),
	mu_demangle_test("_ZN4llvmL14OperandInfo213E", "llvm::OperandInfo213"),
	mu_demangle_test("_ZN4llvmL14OperandInfo214E", "llvm::OperandInfo214"),
	mu_demangle_test("_ZN4llvmL14OperandInfo215E", "llvm::OperandInfo215"),
	mu_demangle_test("_ZN4llvmL14OperandInfo216E", "llvm::OperandInfo216"),
	mu_demangle_test("_ZN4llvmL14OperandInfo217E", "llvm::OperandInfo217"),
	mu_demangle_test("_ZN4llvmL14OperandInfo218E", "llvm::OperandInfo218"),
	mu_demangle_test("_ZN4llvmL14OperandInfo219E", "llvm::OperandInfo219"),
	mu_demangle_test("_ZN4llvmL14OperandInfo220E", "llvm::OperandInfo220"),
	mu_demangle_test("_ZN4llvmL14OperandInfo221E", "llvm::OperandInfo221"),
	mu_demangle_test("_ZN4llvmL14OperandInfo222E", "llvm::OperandInfo222"),
	mu_demangle_test("_ZN4llvmL14OperandInfo223E", "llvm::OperandInfo223"),
	mu_demangle_test("_ZN4llvmL14OperandInfo224E", "llvm::OperandInfo224"),
	mu_demangle_test("_ZN4llvmL14OperandInfo225E", "llvm::OperandInfo225"),
	mu_demangle_test("_ZN4llvmL14OperandInfo226E", "llvm::OperandInfo226"),
	mu_demangle_test("_ZN4llvmL14OperandInfo227E", "llvm::OperandInfo227"),
	mu_demangle_test("_ZN4llvmL14OperandInfo228E", "llvm::OperandInfo228"),
	mu_demangle_test("_ZN4llvmL14OperandInfo229E", "llvm::OperandInfo229"),
	mu_demangle_test("_ZN4llvmL14OperandInfo230E", "llvm::OperandInfo230"),
	mu_demangle_test("_ZN4llvmL14OperandInfo231E", "llvm::OperandInfo231"),
	mu_demangle_test("_ZN4llvmL14OperandInfo232E", "llvm::OperandInfo232"),
	mu_demangle_test("_ZN4llvmL14OperandInfo233E", "llvm::OperandInfo233"),
	mu_demangle_test("_ZN4llvmL14OperandInfo234E", "llvm::OperandInfo234"),
	mu_demangle_test("_ZN4llvmL14OperandInfo235E", "llvm::OperandInfo235"),
	mu_demangle_test("_ZN4llvmL14OperandInfo236E", "llvm::OperandInfo236"),
	mu_demangle_test("_ZN4llvmL14OperandInfo237E", "llvm::OperandInfo237"),
	mu_demangle_test("_ZN4llvmL14OperandInfo238E", "llvm::OperandInfo238"),
	mu_demangle_test("_ZN4llvmL14OperandInfo239E", "llvm::OperandInfo239"),
	mu_demangle_test("_ZN4llvmL14OperandInfo240E", "llvm::OperandInfo240"),
	mu_demangle_test("_ZN4llvmL14OperandInfo241E", "llvm::OperandInfo241"),
	mu_demangle_test("_ZN4llvmL14OperandInfo242E", "llvm::OperandInfo242"),
	mu_demangle_test("_ZN4llvmL14OperandInfo243E", "llvm::OperandInfo243"),
	mu_demangle_test("_ZN4llvmL14OperandInfo244E", "llvm::OperandInfo244"),
	mu_demangle_test("_ZN4llvmL14OperandInfo245E", "llvm::OperandInfo245"),
	mu_demangle_test("_ZN4llvmL14OperandInfo246E", "llvm::OperandInfo246"),
	mu_demangle_test("_ZN4llvmL14OperandInfo247E", "llvm::OperandInfo247"),
	mu_demangle_test("_ZN4llvmL14OperandInfo248E", "llvm::OperandInfo248"),
	mu_demangle_test("_ZN4llvmL14OperandInfo249E", "llvm::OperandInfo249"),
	mu_demangle_test("_ZN4llvmL14OperandInfo250E", "llvm::OperandInfo250"),
	mu_demangle_test("_ZN4llvmL14OperandInfo251E", "llvm::OperandInfo251"),
	mu_demangle_test("_ZN4llvmL14OperandInfo252E", "llvm::OperandInfo252"),
	mu_demangle_test("_ZN4llvmL14OperandInfo253E", "llvm::OperandInfo253"),
	mu_demangle_test("_ZN4llvmL14OperandInfo254E", "llvm::OperandInfo254"),
	mu_demangle_test("_ZN4llvmL14OperandInfo255E", "llvm::OperandInfo255"), );
mu_main(gpl, cxx, RZ_DEMANGLE_OPT_ENABLE_ALL);
